### ISSUE TITLE
HMR doesn't work with create-react-app on Windows

### ISSUE THREAD

**Issue by arseneyr** [react-cosmos/react-cosmos#1069]
### What's wrong?

Hot module reloading does not work with create-react-app and the recommended Cosmos config.

### Steps to reproduce

1. Create a new CRA
2. Add react-cosmos@next
3. Add the recommended Cosmos config:
```
{
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  }
}
```
4. Add a minimal fixture to `src/App.fixture.jsx`:
```
import React from "react";
import App from "./App";

export default () => <App />;
```
5. Start Cosmos
6. Edit `src/App.jsx`

Expected result:
The fixture is reloaded with the new component.

Actual Result:
The webpack bundle is rebuilt but neither the fixture nor the component are reloaded. Reloading the Cosmos page does not work. Need to restart the Cosmos server to pick up changes.

### User info

* Cosmos version: 5.0.0-beta.10
* CRA version: 3.2.0
  * Relevant [webpack config](https://github.com/facebook/create-react-app/blob/7fae307aefe74282f2ffc98e8f1f401ddf5fab3f/packages/react-scripts/config/webpack.config.js)

**Comment by skidding** [comment]
Hi @arseneyr,

I just updated the react-cosmos CRA example repo with the latest deps (the ones you use): https://github.com/react-cosmos/create-react-app-example/commit/671e5c0ba92f17a708e6118708e3ae096f1eed4d

HMR works fine on my end. Can you please test this repo on your machine to see if you get the same experience? Depending on this result we'll know what to investigate next.

**Comment by arseneyr** [comment]
Thanks for the quick response @skidding. I tried cloning the repo and am still getting no HMR. I forgot to mention that I'm on Windows 😕. I'm not an expert on webpack but it looks like the `userDepsLoader` is not getting rerun on changes to the `src/` dir. Perhaps there is something strange going on with directory watching on Windows?

**Comment by arseneyr** [comment]
Update: looks like `webpackLoaderContext.addContextDependency()` can't handle forward slashes on Windows. When I force the watchDirs to have backslashes, HMR works again. Not sure if this is a webpack or watchpack bug.

**Comment by arseneyr** [comment]
I've opened https://github.com/webpack/watchpack/issues/123. This seems like it will be fixed in webpack v5. But in case it's not fixed for v4, could we do a stopgap fix where we either glob the watchDirs (if they are meant to support globs) or exclude them from slash conversion (if they are not)?

**Comment by skidding** [comment]
@arseneyr,

Thanks for looking into this.

If not normalizing slashes for the watch dir paths solves the issue then I will accept a PR that changes [this line](https://github.com/react-cosmos/react-cosmos/blob/b1fb009339c2641a67f583809a3cce4ed46c3040/packages/react-cosmos/src/config/createCosmosConfig.ts#L52) to use `path.resolve` instead of [the `resolvePath` helper](https://github.com/react-cosmos/react-cosmos/blob/b1fb009339c2641a67f583809a3cce4ed46c3040/packages/react-cosmos/src/config/resolve.ts#L5-L8). I would also add a comment above the changed line with a link to this issue to clarify any future confusion.

> This seems like it will be fixed in webpack v5

Out of curiosity, where did you get this hint from?

> either glob the watchDirs

I'd stick with the former solution (omit slash normalizing) because this would involve more changes. At the moment it's convenient because we can simply call `addContextDependency` once for every watch dir.

**Comment by arseneyr** [comment]
> Out of curiosity, where did you get this hint from?

Webpack v5 is using watchpack v2 beta, which I've verified doesn't have this issue.

I've opened a PR with your suggested fix. I don't think any of the regular contributors use Windows to build react-cosmos, so I had to make several small changes for it to build successfully on my machine. Let me know if you're interested in another PR with these changes.

**Comment by skidding** [comment]
@arseneyr Just realized something. HMR and watchDirs are related to separate things. watchDirs listens for new fixture files, and removed ones perhaps. Even if you set watchDirs to an empty array, HMR should still work for files that were bundled in the initial build. 

So maybe HMR still doesn't work for you in `5.0.0-beta.11`? Let me know what are you thoughts and findings on this.

**Comment by arseneyr** [comment]
Interesting. Using the `create-react-app-example` repo, I've confirmed that HMR works on `5.0.0-beta.11` when it didn't on `5.0.0-beta.10`. However, when I remove the `watchDirs` option entirely (or set it to another folder), HMR starts working again on `5.0.0-beta.10`. So I think HMR was always enabled but the `addContextDependency()` behavior was breaking HMR for anything listed in `watchDirs`. The webpack devs say this won't get fixed for v4, so I think this is the best we can do for now.

**Comment by skidding** [comment]
> However, when I remove the watchDirs option entirely (or set it to another folder), HMR starts working again on 5.0.0-beta.10. So I think HMR was always enabled but the addContextDependency() behavior was breaking HMR for anything listed in watchDirs.

Wow, what a messy situation. I really appreciate you took the time to verify this!

Your issue got me playing with my Windows VM today, and I fixed a couple of issues in IE11. I ended up making a bunch of releases in rapid succession due to poor management on my part, but all is good now. But I was only loading Cosmos inside the VM with the server running outside, so I didn’t debug building Cosmos on Windows. Feel free to propose any improvements to that end.
