### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by jamiebuilds** [react-cosmos/react-cosmos#1111]
I thought I'd give some feedback on how the https://reactcosmos.org could be better, I'm happy to help with some of these items, but better to write them down and discuss them first.

- [x] The website works really well as a marketing site right now, but it doesn't really capitalize on that by calling users to action. It should tell them to "Get Started" or "Install" with either a big button to some docs or with a CLI command they can run to get going (maybe even both)
- [x] The website also doesn't really help people who are looking for docs. Linking to "GitHub" is a good start, but it's not my first choice when looking for a nicer documentation experience. It would be great if the website had full documentation, but even just having a "Documentation" link that sends you to the README would be better.
- [x] Design-wise the site is beautiful, but the scroll animations are a bit annoying when you're trying to find something quickly on the page. Firing the animations once on the way down is okay (and maybe making them a little bit shorter time-wise and more subtle), but they should be mostly static after that. It would also be great if the site respected [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) as some users like myself get slightly nauseous when there's lots of animation.
- [x] One of the biggest things that I've found drives adoption of open source projects is finding out that a bunch of bigger companies use the project too. Early on in Babel when I introduced the babeljs.io/users page, it quickly became one of the highest traffic pages. When people see names like Facebook, Netflix, Mozilla, etc., they feel like the project has been well vetted already. You might not even realize how many big companies are using your project until you start asking for them to tell you.
- [x] If possible, it would be great if you could find a way to embed Cosmos itself onto the homepage, even if it is just iframed in. Especially if you could use something like https://react-joyride.com to guide them through all the different features.
- [x] Alternatively, the homepage could use more screenshots demoing the functionality of Cosmos. People like to see what you are talking about more than they like reading about it.
- [x] The [Benefits](https://reactcosmos.org/#benefits) section are good points, but some of them may not be obvious to users and they may want additional information. It would be great to have some sort of subtext that drives each point home and puts them in context. 
- [x] "React Cosmos can be used in powerful ways. Snapshot and visual regression tests are possible [...]" this sounds like a roundabout way of telling people they have to do work to set it up. So for starters, you should try to make both of these really really easy to setup, and second you should emphasize how easy it is to setup. Also "Open Platform" is kinda a bold claim that sounds like marketing, it would be better to say something like "Extensible" 
- [x] I appreciate that you don't bother mentioning Storybook on the website. A lot of users will ask you for that comparison, but it'll only do one of two things: Make the project seem bitter about Storybook, or make it seem like the benefits aren't all that significant. It's much better to focus on making your users so happy they spread the word for you. Focus on what makes Cosmos an amazing tool and the rest really does follow. That being said, you should have something to say to people when they ask you what the difference is from Storybook. I would again focus on the experience of Cosmos over Storybook, and how you're a much more focused project with just React support (for now?) and you're being very detail oriented.
- [x] I also just want to put out there that I think it's important that the website has _all_ of the docs on how to use Cosmos. READMEs don't drive nearly as much adoption as websites, and even really well done docs on GitHub don't have the same impact as a website with even poorly done docs. People will say the project isn't well documented if the site doesn't contain lots of documentation.

Sorry if this was too much of a brain dump. I've worked on a lot of marketing sites for projects like [Babel](https://babeljs.io), [Yarn](https://yarnpkg.com/), and [Flow](https://flow.org) so I have a lot of strong opinions. You've done a great job already though :)

**Comment by skidding** [comment]
Wow, I really appreciate your thoughtful proposals. I get easily overwhelmed by issues so it might take a while to properly address all your ideas, but I wanted to at least reply briefly to let you know that I'm not ignoring or dismissing your input.

The only thing I kinda have an opinion against is moving all docs to the website. Not that it won't have all the benefits you point out, but mostly because I'm very detail oriented like you say (often to a fault) and prefer to not to duplicate stuff like code snippets that READMEs are already optimized for. I'm aware that eventually it makes sense to host your own docs, but it's just one of those things I'd like to postpone for as long as possible. There must be some middle ground, however, as the current website info is indeed slim. Better explanations of the feature set would help a ton, even if we continue to keep the heavy duty docs in the README.

A better call to action, actually having a button that says "docs" 😅, more screenshots (I already put some on [Product Hunt](https://www.producthunt.com/posts/react-cosmos-5)), improving the Benefits section, respecting `prefers-reduced-motion`, all solid points. Also probably best to only animate things once, although I must say I like the playfulness of allowing the users to replay animations by scrolling. I get easily hooked by these sort of silly things but I agree it's borderline annoying. I'd definitely experiment some quicker times, though.

Once again, I'm happy you find React Cosmos worth your time and I appreciate your contributions! :)

**Comment by skidding** [comment]
> If possible, it would be great if you could find a way to embed Cosmos itself onto the homepage, even if it is just iframed in. 

This was the initial plan for this website but then I got derailed with SVGs and transitions. The Cosmonaut looks pretty sharp so no regrets haha. I also abandoned the idea partly because the live instance won't be very usable on mobile, and because "Live demo" is one click away. That said it's still a good idea.

> Especially if you could use something like https://react-joyride.com to guide them through all the different features.

Yes, this kind of onboarding is gold.

**Comment by jamiebuilds** [comment]
If you want to put the docs in markdown, you could also drop them all into a `docs/` folder that can be used to generate the website. I think it would be a pretty significant improvement

**Comment by skidding** [comment]
Here's an update on most of the items mentioned:

> The website works really well as a marketing site right now, but it doesn't really capitalize on that by calling users to action.

"Get started" button added right after the intro splash screen.

![image](https://user-images.githubusercontent.com/250750/72255682-09cc9300-3610-11ea-8b82-0c08cccaa628.png)

> The website also doesn't really help people who are looking for docs. 

Added "docs" secondary action on splash screen.

![image](https://user-images.githubusercontent.com/250750/72255750-3385ba00-3610-11ea-941a-a6e182d50ba4.png)

As well as in the sticky header

![image](https://user-images.githubusercontent.com/250750/72255787-50ba8880-3610-11ea-9695-d7562850bf49.png)

> the scroll animations are a bit annoying when you're trying to find something quickly on the page. Firing the animations once on the way down is okay

Removed some of the animations and made them only fire on the way down (with one exception: if you scroll all the way to top they will fire again on the way down). The content remains static while going back and forth, which is way better. Turns out I also had `prefers-reduced-motion` enabled in my OS. I went back and forth on this and in the end didn't disable the animations when the setting in enabled in the hopes that the current version is tolerable even for people who prefer reduced motion (like myself). I think the most annoying part of the first version was the `background-attachment: fixed` effect that I removed completely.

> One of the biggest things that I've found drives adoption of open source projects is finding out that a bunch of bigger companies use the project too.

You convinced me to reach out to users. I'll get back to this.

> If possible, it would be great if you could find a way to embed Cosmos itself onto the homepage, even if it is just iframed in

Done!

![image](https://user-images.githubusercontent.com/250750/72256091-0b4a8b00-3611-11ea-804c-c77a23f35da9.png)

> Alternatively, the homepage could use more screenshots demoing the functionality of Cosmos.

Added more screenshots on mobile, where the live demo is hidden (but still linked to).

> The Benefits section are good points, but some of them may not be obvious to users and they may want additional information.

Added subtext to each benefit.

![image](https://user-images.githubusercontent.com/250750/72256155-2ddca400-3611-11ea-9366-45bd000178cb.png)

> "React Cosmos can be used in powerful ways. Snapshot and visual regression tests are possible [...]" this sounds like a roundabout way of telling people they have to do work to set it up

Removed "are possible" from the wording.

> Also "Open Platform" is kinda a bold claim that sounds like marketing, it would be better to say something like "Extensible"

Indeed, but a large part of the current roadmap is to match this description. I'll do my best to fulfill it in the coming months :).

> I appreciate that you don't bother mentioning Storybook on the website. A lot of users will ask you for that comparison, but it'll only do one of two things: Make the project seem bitter about Storybook, or make it seem like the benefits aren't all that significant. It's much better to focus on making your users so happy they spread the word for you. Focus on what makes Cosmos an amazing tool and the rest really does follow. That being said, you should have something to say to people when they ask you what the difference is from Storybook. I would again focus on the experience of Cosmos over Storybook, and how you're a much more focused project with just React support (for now?) and you're being very detail oriented.

Added a "Why React Cosmos?" in the main README to address this. It's not on the website, but it is very visible because I've moved the docs to a separate folder.

![image](https://user-images.githubusercontent.com/250750/72256357-ac394600-3611-11ea-90d4-3d104fd09214.png)

Huge thanks to @jamiebuilds for his thoughtful feedback!

I'm going to keep this open because there are still some unaddressed ideas.

**Comment by maxstoyanov** [comment]
Just to throw in my own thoughts: I'd like to second that hosting documentation on the main site is a necessity. The folder navigation and the default rendering of markdown in the repository is not that good. Discoverability is king when it comes to docs.

My first impression was: "Oh, this is a small and immature side project..."
I judge open source projects mainly by their documentation.

**Comment by ThaisRobba** [comment]
Small addendum: twitter now blocks viewing tweets for non-users, maybe the points made in the tweets could be brought into the website?

**Comment by skidding** [comment]
Left this open over the years until I could honestly check the last bullet related to having a docs website instead of one long README. I'm happy to say that bullet is now more than checked. The current docs are beautiful (thanks to Nextra) and the website is looking sharp. The home page is rather simple but I think it conveys what React Cosmos does, shows it and gives enough context to dig deeper. More professional and hopefully with fewer false claims than the previous site: https://reactcosmos.org/

Many thanks to @jamiebuilds for the original feedback. I'm closing this for closure, but I welcome anyone to further review the current website and docs. Oh and Merry Christmas! 🥳
