### ISSUE TITLE
Subfolder Export 404

### ISSUE THREAD

**Issue by luckyraul** [react-cosmos/react-cosmos#1149]
### What's wrong?

If you export to subfolder (as default) got 404 to /_renderer.html

### Steps to reproduce

1.  export to subfolder
2. open in browser
3. 404 on /_renderer.html
### Screenshots

**Comment by skidding** [comment]
@luckyraul Try setting the `publicUrl` config to `"./"` (relative path) and let me know if it fixes your problem.

Like this
https://github.com/react-cosmos/react-cosmos/blob/c0dedd67cfbbb241068d248053f580f0c7bcdf23/website/cosmos.config.json#L4

**Comment by luckyraul** [comment]
It's okay, but definitely you need to fix this issue, as by default export is in folder, not root (/cosmos-export)

**Comment by skidding** [comment]
I don't know how to make static exports work from nested paths by default, without breaking anything else. If I make the `publicUrl` relative by default, then all app URLs will be relative to the current URL instead of relative to the app root. This breaks down as soon as your app has nested routes. I believe even create-react-app requires defining a base URL (`homepage` in package.json?) if you want to serve your app from a nested path.

In the meantime I added a Troubleshooting section and created a detailed [dev document](https://github.com/react-cosmos/react-cosmos/blob/43d2dbf46239f08bb7afb5fb19e3fdcf6f4c88ed/docs/dev/publicUrl.md) with all the intricacies of the `publicUrl` option.
