### ISSUE TITLE
Every component's render function runs twice every time it is shown in cosmos

### ISSUE THREAD

**Issue by vitalybe** [react-cosmos/react-cosmos#1159]
### What's wrong?

Every component is rendered **twice** every time it loads.

If this isn't a known issue, I can try to reproduce it in a blank environment.

### Steps to reproduce

1. Create a simple component and add it a fixture, e.g:
```
import React from 'react';

export function Hello({ greeting, name }) {
  console.log("RENDERING");
  return <h1>{greeting}, {name}!</h1>;
}
```
1. Load the fixture in react-cosmos, **RENDERING** message appears twice.

### User info

- Cosmos version: 5.0.6
- Webpack: 4.41.2

**Comment by skidding** [comment]
Hi @vitalybe,

In most cases this is expected. When you load a fixture like `export default <Hello greeting="Aloha" name="Alexa" />`, Cosmos saves a copy of the props value in state for you to edit them in the props panel. This causes a re-render.

Is this impairing you in any way? FYI The React team often stresses that we shouldn't worry about re-renders in development because components should be idempotent, which means that no matter how many times a component is rendered it will provide the way output.

**Comment by vitalybe** [comment]
I just wasn't expecting it, coming from storybook, so I thought I was doing something wrong.  You're right however, it shouldn't matter to my components.

BTW, thanks for your project, I like it a lot and it works very well!

**Comment by skidding** [comment]
Awesome. Good luck!
