### ISSUE TITLE
Conflicting type exports across packages

### ISSUE THREAD

**Issue by andyrichardson** [react-cosmos/react-cosmos#1166]
### What's wrong?

Cosmos exports conflict with eachother meaning importing 'react-cosmos' fails in typescript.

<details>
  <summary>Error log</summary>

```
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,10): error TS2440: Import declaration conflicts with local declaration of 'FixtureDecoratorId'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,30): error TS2440: Import declaration conflicts with local declaration of 'FixtureElementId'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,48): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateUnserializableValue'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,81): error TS2440: Import declaration conflicts with local declaration of 'FixtureStatePrimitiveValueType'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,113): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateObjectValueType'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,142): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateArrayValueType'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,170): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateValueType'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,193): error TS2440: Import declaration conflicts with local declaration of 'FixtureStatePrimitiveValue'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,221): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateObjectValue'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,246): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateArrayValue'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,270): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateValue'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,289): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateValues'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,309): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateValuePair'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,332): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateValuePairs'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,356): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateProps'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,375): error TS2440: Import declaration conflicts with local declaration of 'FixtureStateClassState'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,399): error TS2440: Import declaration conflicts with local declaration of 'FixtureState'.
node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts(1,413): error TS2440: Import declaration conflicts with local declaration of 'SetFixtureState'.
node_modules/react-cosmos/dist/config/index.d.ts(1,10): error TS2440: Import declaration conflicts with local declaration of 'CosmosConfig'.

```

</details>

### Steps to reproduce

Spin up [this sandbox](https://codesandbox.io/s/interesting-tree-7ty56) and run "yarn start"

### Additional context

~Conflicts seem to be related to global/namespace declarations. I suspect having `index.d.ts` at the root of projects is somehow related to this.~

The issue is because types with the same name are being _declared_ in multiple packages:

```tsx
export declare type X = //...
```

Removing "declare" so that types are not globally namespaced (i.e. `export type X`) would prevent this issue and conflicts with any unrelated libraries.

Doing this, types could still be used via imports:

```tsx
import { ExportedType } from 'react-cosmos'; 
```

Side note - if you want to remove some redundancy, types could be declared in `react-cosmos` and imported in other cosmos packages. TS wouldn't have an issue with circular imports.

**Comment by skidding** [comment]
I think this due to a change in TypeScript 3.7 or 3.8. I remember trying to upgrade once or twice and seeing errors related to how those types are re-exported, and returned to 3.6. But it would be great to solve this and get on latest TypeScript.

Ideally types would be reexported like this

> packages/react-cosmos-shared2/src/fixtureState/index.ts

```diff
-import {
+export {
   FixtureDecoratorId,
   FixtureElementId,
   FixtureStateUnserializableValue,
@@ -18,27 +18,6 @@ import {
   FixtureState,
   SetFixtureState
 } from './shared';
-
-// Types can't be re-exported because Babel (see root tsconfig.json)
-export type FixtureDecoratorId = FixtureDecoratorId;
-export type FixtureElementId = FixtureElementId;
-export type FixtureStateUnserializableValue = FixtureStateUnserializableValue;
-export type FixtureStatePrimitiveValueType = FixtureStatePrimitiveValueType;
-export type FixtureStateObjectValueType = FixtureStateObjectValueType;
-export type FixtureStateArrayValueType = FixtureStateArrayValueType;
-export type FixtureStateValueType = FixtureStateValueType;
-export type FixtureStatePrimitiveValue = FixtureStatePrimitiveValue;
-export type FixtureStateObjectValue = FixtureStateObjectValue;
-export type FixtureStateArrayValue = FixtureStateArrayValue;
-export type FixtureStateValue = FixtureStateValue;
-export type FixtureStateValues = FixtureStateValues;
-export type FixtureStateValuePair = FixtureStateValuePair;
-export type FixtureStateValuePairs = FixtureStateValuePairs;
-export type FixtureStateProps = FixtureStateProps;
-export type FixtureStateClassState = FixtureStateClassState;
-export type FixtureState = FixtureState;
-export type SetFixtureState = SetFixtureState;
-
 export {
   isString,
   isNumber,
```

But this doesn't work with `isolatedModules` set to `true`, which is required for Babel to know how to build Cosmos packages.

https://github.com/react-cosmos/react-cosmos/blob/0b6d43008ddef1ba50df9cccc89f9e15394e78cf/tsconfig.json#L21-L29

> Side note - if you want to remove some redundancy, types could be declared in `react-cosmos` and imported in other cosmos packages. TS wouldn't have an issue with circular imports.

_Maybe_ this would fix the issue? I prefer having types close their associated code, but if this is the only way to get us on the latest TypeScript I'm open to it.

I don't have enough head space right now to get to the bottom of this, so I'll have to come back. If you or anyone else is willing to give a hand I'm definitely open to contributions on this!

**Comment by skidding** [comment]
Interesting. I've upgrade TS and disabled `isolatedModules` and Babel still builds successfully: https://github.com/react-cosmos/react-cosmos/pull/1167. Maybe something changed in the ecosystem this past months or I'm just missing something.

**Comment by skidding** [comment]
OK, I figured out why (I thought) we needed to use `isolatedModules`. 

1. Babel expects `isolatedModules: true` because it analyses modules independently ([context](https://github.com/chalk/chalk/pull/296#issuecomment-431625641)).
2. Babel still compiles successfully with `isolatedModules: false`, because Babel only needs to strip the types and apply other transforms on the source code. Type safety is checked via `tsc` on the monorepo as a whole.
3. The only issue is if you look at the build log, you see Babel complaining about re-exported types because it can't verify them across files. The "invalid" imports are ignored and don't affect the build. Type definitions are generated using `tsc` in a separate task.
  ![image](https://user-images.githubusercontent.com/250750/76020074-720e6580-5f2b-11ea-9c5b-48523d1258e3.png)

Half a year later, I decided I don't really care about those warnings. I prefer not being forced to write code in a certain way to make the Babel happy. So I disabled `isolatedModules`, which allowed me to change those re-exported types to regular `export { SomeType } from './someModule`.

@andyrichardson Can you give `react-cosmos@5.0.9` a go? I think it should now work well with latest TypeScript. https://codesandbox.io/s/flamboyant-ptolemy-zp34f

**Comment by andyrichardson** [comment]
Sorry I didn't respond to this sooner - looks like it's fixed 🙏
