### ISSUE TITLE
Nicer URL

### ISSUE THREAD

**Issue by jkavalec** [react-cosmos/react-cosmos#1211]
I am not sure whether there is an option to set this up already.

When I have a component inside cosmos, its URL is in this shape: `http://localhost:5000/_renderer.html_fixtureId=%7B"path"%3A"src%2Feditors%2Fsketch%2F__fixtures__%2FSketch.fixture.tsx"%2C"name"%3Anull%7D`

I want to have TestCafe tests running tests over components, so I would like to navigate to fixtures easily like this:
 `http://localhost:5000/folder-with-some-components/button/rounded-button` 
instead easy to write URL above, is there any way to achieve this?

**Comment by skidding** [comment]
Hi @jkavalec,

Since fixtures are ID-ed by file path, your example would need to reference `src/editors/sketch/__fixtures__/Sketch.fixture.tsx`. Fixture files can export more than one fixture, which is why there is also a `name` argument in the URL. You need `/_renderer.html` because just the `/` path loads the React Cosmos UI, instead of the full screen component mode that you mentioned. Another consideration is the static export, which would be more complicated to generate if the URL contained the fixture file path directly instead of having it as query string.

This is just more context, but the answer is no. I agree the URLs are not too pretty. You can, however, make a small helper function that generates the URL like

```ts
(fixtureId) => `http://localhost:5000/_renderer.html?_fixtureId=${JSON.stringify(encodeURIComponent(fixtureId))}`
```

 where `fixtureId` is of type `{ path: string, name: null | string }` where `path` is the fixture file path relative to your project root.

And btw, in case you can make use it of, in a Node environment you can call [getFixtures2](https://github.com/react-cosmos/react-cosmos/tree/master/docs#fixtures-1) to get a list of all your fixtures.

**Comment by skidding** [comment]
Closing this for now. Feel free to propose an RFC if my answer isn't satisfactory and you feel strongly about this: https://github.com/react-cosmos/rfcs.
