### ISSUE TITLE
Waiting on Renderer - webpack - _renderer.html does not exist, is not created

### ISSUE THREAD

**Issue by ericwhitefield** [react-cosmos/react-cosmos#1220]
The Cosmos UI in the browser is waiting for the renderer forever. In the browser inspector network tab it is clearly not able to fetch _renderer.html. The error is correct because _renderer.html was never created by: $ yarn cosmos

This can be confirmed by looking at the file output from: $ yarn cosmos:export

This happens when webpack.config.js is implementing the plugin: HtmlWebpackPlugin 

Example:
           new HtmlWebpackPlugin({
                filename: path.resolve(__dirname, 'build/index.html'),
                template: path.resolve(__dirname, 'src', 'index.html'),
            }),

Note: It has been said elsewhere that HtmlWebpackPlugin is a required devDependency for Cosmos. The issue here is not about the dependency, but specifically about implementing it in webpack.config.js

Solution: remove HtmlWebpackPlugin implementation completely from webpack.config.js

If you need HtmlWebpackPlugin plugin then one possible solution is to create a webpack config just for Cosmos and use cosmos.config.json to point to it.

(Just answering my own question here, hope it helps others)

**Comment by skidding** [comment]
Hi @ericwhitefield,

You're right, Cosmos adds HtmlWebpackPlugin to your webpack config if it doesn't find it already in the `plugins` list. It also, however, alters an existing HtmlWebpackPlugin instance found in your webpack config, provided it's the index one – some people have multiple HTMLs configured in a webpack config.

The issue, it seems, is that Cosmos doesn't realize your HtmlWebpackPlugin is the index one, because you use an absolute path for `filename`. Currently only a HWP instance with an `index.html` filename is considered. See here:

https://github.com/react-cosmos/react-cosmos/blob/1a54f3cf37afd0440d05a7a06897994bdbf56712/packages/react-cosmos/src/plugins/webpack/webpackConfig/htmlPlugin.ts#L58-L71

I think we can improve this detection, and on line 59 we can could instead also match if the filename ends with `/index.html`.

Interested to make this contribution? 😎

**Comment by ericwhitefield** [comment]
Thx @skidding, so that makes a lot of sense now. For my use case I could get by with a much simpler config. This works for both my build and Cosmos.

new HtmlWebpackPlugin({
     template: 'src/index.html'
}),

Maybe I will make a PR for the detection. Separately, have you thought about making it more auditable? Perhaps by writing out the altered webpack config?

**Comment by skidding** [comment]
> Perhaps by writing out the altered webpack config?

No really, but good point. I wouldn't just print the config in the terminal as it would be noise 99% of the time, but there might be ways to improve. Eg. In the "renderer error" screen we could add a button to "copy generated webpack config to clipboard". And/or to figure out in code that a HtmlWebpackPlugin was found in the user's webpack config but couldn't be repurposed by Cosmos because of filename not matching, and print a warning in the terminal. I'm just afraid it's too much information for most to grasp. Generally I try to prevent errors because people are already sick of dealing with compiler and bundler config :).

**Comment by skidding** [comment]
@ericwhitefield Pushed a fix in #1226 to address this. Can you please try `5.5.0-alpha.2` and see if it works with your initial webpack/HtmlWebpackPlugin config? Thanks!
