### ISSUE TITLE
Resolve yarn 2 warnings

### ISSUE THREAD

**Issue by davidroeca** [react-cosmos/react-cosmos#1266]
### What's wrong?

When installing `react-cosmos` from yarn 2, the following warnings are raised:

```shell
$ yarn --version
2.1.1
$ yarn install
➤ YN0002: │ react-cosmos-shared2@npm:5.5.0 doesn't provide react@^0.14.8 || ^15.0.1 || ^16.0.0 requested by react-element-to-jsx-string@npm:14.3.1
➤ YN0002: │ react-cosmos-shared2@npm:5.5.0 doesn't provide react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 requested by react-element-to-jsx-string@npm:14.3.1
➤ YN0002: │ react-cosmos@npm:5.5.0 doesn't provide webpack@^4.0.0 requested by webpack-dev-middleware@npm:3.7.2
```

### Steps to reproduce

1. [Install yarn](https://yarnpkg.com/getting-started/install#per-project-install)
2. `yarn init` a new project
3. Within that new project `yarn set version latest`
4. Experience the warnings

### Screenshots

None necessary.

### User info

~- Server terminal output~
~- Browser console output~
- Cosmos version: 5.5.0
~- If bug occurred on upgrade: Working Cosmos version~
~- Cosmos config~
~- If applicable: webpack version~
~- If applicable: webpack config~

### Additional context

In order to resolve these warnings, `react-cosmos` and `react-cosmos-shared2` should list out these as either `peerDependencies` or `dependencies`.

Some more information on behavior of the warning: https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency

**Comment by skidding** [comment]
Cosmos doesn't put react/react-dom into `dependencies` to avoid duplicate React copies. It used to have them in `peerDependencies` for a while until it got annoying because it produced install warnings when people were using slightly different versions that were still compatible, and also when – and I'm not 100% about this – your codebase relied on another package to install these peer dependencies. So for example you use Create React App, which comes with React and webpack embedded, so your project doesn't have them listed as dependencies. Then you install Cosmos and it complains that it can't find those peer dependencies, even tho they are installed by CRA indirectly. This scenario needs to be validated, but I'm more than happy to get rid of these warnings if we can do it without introducing other warnings or bigger issues.

**Comment by davidroeca** [comment]
I agree that it's a bit annoying that yarn forces libraries with dependencies that have peer dependencies to re-declare them. I guess it's just a way for yarn to bubble up warnings? What if these peer dependencies were just far more broad than those of `react-cosmos-shared2`, the most extreme of which would be something like:

```js
{
  "peerDependencies": {
    "react": "*",
    "react-dom": "*",
    "webpack": "*",
    ...
  },
  ...
}
```

I'll experiment around with how yarn 2 treats with these sorts of peer dependency chains, and confirm whether the more constrained versions from a parent library are still enforced. Will report back the results.

**Comment by davidroeca** [comment]
Ok I confirmed that these `"*"` dependencies effectively defer versioning restrictions to modules that they depend on. This behavior works consistently on:
```shell
$ npm --version
6.14.8
$ yarn --version
1.22.4
$ yarn --version
2.1.1
```

**Comment by davidroeca** [comment]
Found a work-around for myself in my yarn configuration https://yarnpkg.com/configuration/yarnrc#packageExtensions - works for now, though not the most ideal

**Comment by skidding** [comment]
@davidroeca PnP compatibility should be fixed in v6.

- Please check out the [migration guide](https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md) if you want to try it out. 
- Also updated the [pnp-example](https://github.com/react-cosmos/pnp-example) repo and created a [GitHub Actions workflow](https://github.com/react-cosmos/react-cosmos/blob/6aefc11752c44ad442dfeccd47858f59aa7cf605/.github/workflows/test-pnp.yml) that makes sure Cosmos still works well in that repo after every commit.
- In case I missed something let me know and we'll strengthen the example repo and automated workflow to prevent PnP issues from cropping up again in the future.
