### ISSUE TITLE
Proxy http requests to different port

### ISSUE THREAD

**Issue by brojd** [react-cosmos/react-cosmos#1268]
I have an Next.js app and I introduced `react-cosmos` in the project. I configured Next.js to proxy requests from `localhost:3000` to `localhost:9000` where my server is running. Is there a way to apply the same for `react-cosmos`? 

The reason is that I'd like to use `react-cosmos` also for components that can make some requests to BE without mocking them.

**Comment by skidding** [comment]
Indeed it's possible. Unfortunately there's no better docs at the moment, but you can see the available options in the [config schema](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos/config.schema.json#L92-L131). More context [here](https://github.com/react-cosmos/react-cosmos/pull/1078).

Let me know if this answers your question.

**Comment by brojd** [comment]
@skidding Thanks for quick answer, that's exactly what I need.

I added `cosmos.config.json` file and added:
```
{
  "httpProxy": {
    "/api": {
      "target": "http://localhost:9000/api",
      "secure": false
    }
  }
}
```

in order to proxy all requests to `/api` to different port (`cosmos` is running on :5000). Terminal confirms the proxy config: "[HPM] Proxy created: /api  -> http://localhost:9000/api"

However it doesn't seem to work.
![image](https://user-images.githubusercontent.com/12073649/94830789-3a599480-040c-11eb-8ce7-4605f1d9296f.png)

If I hit the http://localhost:9000/api/form-example in browser or postman it works ok. So something wrong with proxy. Any idea?

**Comment by skidding** [comment]
I'm not sure but my first instinct would be to try setting the target to just `http://localhost:9000`, as the `/api` path will probably be preserved.

If that doesn't work, maybe you can do some debugging because the http proxy functionality is all contained in [this small file](https://github.com/react-cosmos/react-cosmos/blob/6619ea2823e3b14df404844e91e7efef2c770bd7/packages/react-cosmos/src/plugins/httpProxy.ts). You can open this (compiled) file in `node_modules/react-cosmos/dist/plugins/httpProxy.js` if you want to console log in your codebase.

Let me know if you figure it out ✌️

**Comment by brojd** [comment]
That was it, thanks a lot @skidding !
