### ISSUE TITLE
[Tutorial / Documentation] Link from the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [react-cosmos/react-cosmos#1283]
Hey there guys,

I have recently heard about COSMOS; I think it refers to react-cosmos but not
sure yet.

I know quite a lot of ruby; and a bit of javascript. But getting "back into the thick
of things" isn't that trivial, so I'd love a tutorial for cosmos in particular.

The main README does not mention any of such. If such a tutorial exists,
would it be possible to add a link to it from the main README?

If no such tutorial exists, would it be possible to add one? This does not
have to cover everything; really just more a slightly more extensive 
"getting started" guide, ideally catering towards people who are semi-competent
but lack quite a lot of knowledge (thus, they are not quite newbies, more 
experienced folks, but may lack a LOT of knowledge about javascript
and other modern frameworks in use; my knowledge is still, sort
of, stuck in the 1990s, early 2000s, even though I know about microframeworks
etc... - just not from a USAGE point of view).

**Comment by brianespinosa** [comment]
@rubyFeedback in addition to the README, did you take a look at https://reactcosmos.org/? There's a lot of stuff on there that might be more what you are looking for. The site is linked from the right column in Github. If it is not linked from the README, that would probably be a good add.

If that is _not_ what you are looking for and you already saw it, please disregard this suggestion. And welcome back to code-land.

**Comment by skidding** [comment]
Hi @rubyFeedback,

There is a link to the documentation in the main readme:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/250750/103958110-e837b600-5154-11eb-9c16-05723467cc7e.png">

**[Here are the docs](https://github.com/react-cosmos/react-cosmos/tree/master/docs)**

We don't have a tutorial unfortunately, but there is a "getting started" section. It does require JavaScript & React knowledge, so hopefully it's useful to you. Feedback appreciated.

> I have recently heard about COSMOS; I think it refers to react-cosmos but not sure yet.

Not sure either, maybe you heard about React Cosmos, maybe about the [Cosmos blockchain](https://cosmos.network), or maybe about the all encompassing [Cosmos](https://en.wikipedia.org/wiki/Cosmos:_A_Personal_Voyage) 😄. To make sure you're in the right place, what exactly are you looking for?

PS. I deleted your other comment from "Who uses React Cosmos?" because that's a thread for people who use Cosmos to post links and logos of their company for the Cosmos website.
