### ISSUE TITLE
Startup cosmos with errors using latest create-react-app

### ISSUE THREAD

**Issue by ChenyangLyu** [react-cosmos/react-cosmos#1367]
### What's wrong?

Startup cosmos with errors using latest create-react-app

### Steps to reproduce

1. Create a new project by CRA

     ```
     npx create-react-app cosmos-test
     ```
2. Add `react-cosmos` into project devDependencies

     ```
     yarn add cosmos --dev
     ```
3. Add `cosmos.config.json` into project root dir

     ```
     {
       "staticPath": "public",
       "watchDirs": ["src"],
       "webpack": {
         "configPath": "react-scripts/config/webpack.config"
       }
     }
     ```
4. Add cosmos start cmd to package.json

    ```
    {
      "cosmos": "cosmos"
    }
    ```

5. Start cosmos

    ```
    yarn cosmos
    ```
    

### Screenshots

_Nothing_

### User info

- Server terminal output

    ```
    [cosmos-test] → yarn cosmos
    yarn run v1.22.15
    warning ../../../package.json: No license field
    $ cosmos
    [Cosmos] Using cosmos config found at cosmos.config.json
    [Cosmos] Serving static files from public
    [Cosmos] See you at http://localhost:5000
    [Cosmos] Using webpack config found at node_modules/react-scripts/config/webpack.config.js
    [Cosmos] Building webpack...
    webpack built 8daeefcd21f631328dd1 in 7072ms
    assets by status 2.6 MiB [cached] 3 assets
    runtime modules 26.1 KiB 12 modules
    modules by path ./node_modules/ 2.45 MiB 221 modules
    modules by path ./src/components/*.js 723 bytes
    ./src/components/button.fixture.js 326 bytes [built] [code generated]
    ./src/components/button.js 397 bytes [built] [code generated]
    ws (ignored) 15 bytes [optional] [built] [code generated]

    WARNING in ./node_modules/@base2/pretty-print-object/dist/index.js
    Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
    Failed to parse source map from '/Users/lvchenyang/Projects/learn/cosmos-test/node_modules/@base2/pretty-print- 
    object/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/lvchenyang/Projects/learn/cosmos- 
    test/node_modules/@base2/pretty-print-object/src/index.ts'
     @ ./node_modules/react-element-to-jsx-string/dist/cjs/index.js 11:24-61
     @ ./node_modules/react-cosmos-shared2/dist/fixtureState/createValues.js 9:34-81
     @ ./node_modules/react-cosmos-shared2/dist/fixtureState/index.js 273:20-45
     @ ./node_modules/react-cosmos-shared2/dist/FixtureLoader/useValue/useCurrentValue.js 10:20-49
     @ ./node_modules/react-cosmos-shared2/dist/FixtureLoader/useValue/index.js 10:23-51
     @ ./node_modules/react-cosmos-shared2/dist/FixtureLoader/index.js 73:16-37
     @ ./node_modules/react-cosmos-shared2/FixtureLoader.js 1:0-48
     @ ./node_modules/react-cosmos/dist/dom/DomFixtureLoader.js 10:21-66
     @ ./node_modules/react-cosmos/dist/dom/index.js 26:24-53
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 5:11-34

    WARNING in DefinePlugin
    Conflicting values for 'process.env'

    1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

    2 warnings have detailed information that is not shown.
    Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

    ERROR in ./src/components/button.fixture.js 3:0-58
    Module not found: Error: You attempted to import /Users/lvchenyang/Projects/learn/cosmos-test/node_modules/react/jsx-dev- 
    runtime which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
    You can either move it inside src/, or add a symlink to it from project's node_modules/.
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 5:0-101 10:38-46
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 15:17-38 29:2-34:4

    ERROR in ./src/components/button.js 2:0-26
    Module not found: Error: You attempted to import /Users/lvchenyang/Projects/learn/cosmos-test/node_modules/react which falls 
    outside of the project src/ directory. Relative imports outside of src/ are not supported.
    You can either move it inside src/, or add a symlink to it from project's node_modules/.
     @ ./src/components/button.fixture.js 2:0-30 4:36-42
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 5:0-101 10:38-46
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 15:17-38 29:2-34:4

    ERROR in ./src/components/button.js 3:0-58
    Module not found: Error: You attempted to import /Users/lvchenyang/Projects/learn/cosmos-test/node_modules/react/jsx-dev-runtime which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
    You can either move it inside src/, or add a symlink to it from project's node_modules/.
     @ ./src/components/button.fixture.js 2:0-30 4:36-42
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 5:0-101 10:38-46
     @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 15:17-38 29:2-34:4

    webpack 5.67.0 compiled with 3 errors and 3 warnings in 7072 ms
    ```

- Browser console output
- Cosmos version
  ```
   ^5.6.7
  ```
- If bug occurred on upgrade: Working Cosmos version
- Cosmos config
   ```
   {
     "staticPath": "public",
     "watchDirs": ["src"],
     "webpack": {
       "configPath": "react-scripts/config/webpack.config"
     }
   }
   ```
- If applicable: webpack version
   ```
   webpack: 5.67.0
   react-scripts: 5.0.0
   ```

- If applicable: webpack config

### Additional context

_No more context_

**Comment by brianespinosa** [comment]
I am pretty sure this is an issue with CRA. It does checks to make sure there are not imports happening outside of the `/src` directory where the rest of the application code is running.

> Relative imports outside of src/ are not supported.

Are the components you are trying to import located outside the `/src` directory where your fixture files are?

**Comment by ChenyangLyu** [comment]
> Are the components you are trying to import located outside the `/src` directory where your fixture files are?

My answer is NO.

- I just initialized a project following the process in my question above based on CRA and created a `Button` component in the `src/components` folder. Then created a fixture file named `button.fixture.js` in the same folder.

- If I changed the version of `react-scripts` from `5.0.0` to `4.0.3`, `react-cosmos` could successfully start without any exceptions.

- So my conclusion is that the current version of `react-cosmos` is not yet compatible with `react-scripts v5` of the CRA?

**Comment by gcwiak** [comment]
I experience exactly the same problem as @ChenyangLyu. 
My application is fairly simple and the latest `react-cosmos` `5.6.7` used to work perfectly fine on `react-scripts` `4.0.3`, but stopped to work with the above errors after upgrading `react-scripts` to `5.0.0`.

**Comment by brianespinosa** [comment]
I have not made this update myself, but I actually had plans to tackle this today. My use case has some fairly complicated overrides needed to the `react-scripts` webpack config so I might be able to shed some more light on what is actually going on in there. I'll report back if I can find the root cause.

If someone has a chance to set up a minimum repro case, it would probably be helpful for @skidding to take a look at too.

**Comment by gcwiak** [comment]
> If someone has a chance to set up a minimum repro case, it would probably be helpful for @skidding to take a look at too.

I have created sample repo reproducing the issue - plain CRA created with
`npx create-react-app cra-vs-react-cosmos --template typescript --scripts-version 4.0.3`

I start React Cosmos with `npm run cosmos`.

* on this brach React Cosmos works fine: 
https://github.com/gcwiak/cra-vs-react-cosmos/tree/cra_4-react_cosmos

* on the other, with CRA upgraded to v5, the problem is reproduced: 
https://github.com/gcwiak/cra-vs-react-cosmos/tree/cra_5-react_cosmos

**Comment by skidding** [comment]
Hi all, thanks for reporting this!

It seems that Create React App 5 added [ModuleScopePlugin](https://github.com/facebook/create-react-app/blob/428ddb683193e548043a4a7edac73d2857386a4c/packages/react-dev-utils/ModuleScopePlugin.js) – a webpack resolve plugin – to their webpack config. This allows them to prevent a common error where people try to import source files from outside the project `src`, which wouldn't work anyway because CRA doesn't compile non-src files.

Cosmos forces some dependencies used by webpack loaders to resolve from the project root, which ends up importing node_modules paths. This is an implementation detail that eases Cosmos development when you symlink a local Cosmos clone in another local repository. It's not an issue because those dependencies don't need compilation. I can't be 100% sure without looking at this more closely but it's probably safe to disable `ModuleScopePlugin` inside Cosmos.

Here's a simple way to fix this in your projects. Create a `webpack.override.js` in your project (or update an existing one) with the following code:

```js
module.exports = (webpackConfig, env) => {
  const { resolve } = webpackConfig;
  resolve.plugins = resolve.plugins.filter(
    p => !isInstanceOf(p, 'ModuleScopePlugin')
  );
  return webpackConfig;
};

function isInstanceOf(instance, name) {
  return instance.constructor && instance.constructor.name === name;
}
```

It works with a fresh CRA 5 installation. Please try it out and let me know if it works in your projects as well. If this approach proves to have no intended side effects we can quickly publish a patch that automatically disables the `ModuleScopePlugin` resolve plugin under the hood.

**Comment by skidding** [comment]
Just published `react-cosmos@5.6.8` which takes care of this automatically, without needing the `webpack.override.js` fix mentioned above. Please try it out and let me know if it works for everyone.

**Comment by fauxparse** [comment]
@skidding I'm still seeing this on 5.7.2...

**Comment by skidding** [comment]
> @skidding I'm still seeing this on 5.7.2...

Can you create a minimal example repo with your CRA version and this error? I will take a look. Maybe CRA renamed the `ModuleScopePlugin` loader or made some other changes to their webpack config.
