### ISSUE TITLE
how to use this without webpack

### ISSUE THREAD

**Issue by hesxenon** [react-cosmos/react-cosmos#1393]
First of all, I really appreciate you putting in the work of creating a component testing framework _and_ making it bundler agnostic. It's what made me drop storybook ;)

Your docs say "how you compile your code is 100% your business" and that we can make it work with other bundlers. I don't see any guidance on _how_ to do this though? What are the important steps? How does react-cosmos look for the renderer html? Where do I register my custom logic? Is there a `require('react-cosmos').listen(12345)' step?

I think it would be great if you could tell us _how_ to integrate other bundlers. I'd be willing to write up a "how-to" guide with esbuild if you could point me in the right direction.

**Comment by skidding** [comment]
@hesxenon Still interested? :)

**Comment by hesxenon** [comment]
I'll have to re-evaluate react cosmos, but yeah, basically I am still
interested :)

**Comment by skidding** [comment]
> I'll have to re-evaluate react cosmos, but yeah, basically I am still
> interested :)

Great.

So if you install `react-cosmos@next` (v6) it no longer comes with webpack built-in. It's going to read your fixtures and start the Cosmos UI without any renderer to connect to.

> What are the important steps? How does react-cosmos look for the renderer html? Where do I register my custom logic? Is there a `require('react-cosmos').listen(12345)' step?

No need to start Cosmos programatically, the `cosmos` CLI command will do. But you'll need to set `rendererUrl` in your Cosmos config, as well as to serve a Cosmos renderer on that URL.

Say your `cosmos.config.json` looks like this:

```json
{
  "port": 5000,
  "rendererUrl": "http://localhost:5001"
}
```

On port 5001 you'd have to serve an app that does this:

```js
import { mountDomRenderer } from 'react-cosmos-dom';

import fixture1 from './src/__fixtures__/fixture1.js';
import fixture2 from './src/__fixtures__/fixture2.js';
import decorator from './src/cosmos.decorator.js';

mountDomRenderer({
  rendererConfig: {},
  fixtures: {
    'src/__fixtures__/fixture1.tsx': { module: { default: fixture0 } },
    'src/__fixtures__/fixture2.ts': { module: { default: fixture1 } },
  },
  decorators: {
    'src/cosmos.decorator.tsx': { module: { default: decorator } },
  },
});
```

This example is more for demonstration purposes because you shouldn't manually import fixture and decorator files to pass them to the renderer. Cosmos will take care of that for you.

With a plugin this happens under the hood, but with a DYI implementation you can run cosmos with the `--external-userdeps` flag to generate all the file mappings and inputs you need.

```
npm run cosmos --external-userdeps
```

This will generate a `cosmos.userdeps.js` file that stays up to date while the Cosmos server is running (and that you can gitignore).

Now your renderer is simplified to this:

```js
import { mountDomRenderer } from 'react-cosmos-dom';
import { rendererConfig, fixtures, decorators } from './cosmos.userdeps.js';

mountDomRenderer({ rendererConfig, fixtures, decorators });
```

Or even:

```js
import { mountDomRenderer } from 'react-cosmos-dom';
import * as mountArgs from './cosmos.userdeps.js';

mountDomRenderer(mountArgs);
```

Serve an app on `localhost:5001` with this index module and you've got yourself a custom Cosmos setup.

To build a Cosmos plugin you'll want to consider extra stuff like hot reloading and static exports. If you're interested in that let me know and I can provide more info. There's a [Vite plugin](https://github.com/react-cosmos/react-cosmos/tree/main/packages/react-cosmos-plugin-vite) available now that covers all of this with little code.

Let me know if you have any feedback. Trying to make this as user friendly as possible and then publish official docs.
