### ISSUE TITLE
Setup of React Native not clear

### ISSUE THREAD

**Issue by ruanpotgieter95** [react-cosmos/react-cosmos#1407]
I am looking to move away from Storybook ( using old versions ), and found react-cosmos. 

It is exactly what we need but I can't seem to get it to work on react-native. Tried following the guides with no luck. 
Looked at the example project with react-native but it is outdated ( 4 years old ) and using expo. 

Please provide a react-native section where it explains exactly what needs to be done to setup react-cosmos with a blank react-native project. Reusing previous sections of documentation makes it unclear what is required or not. 

Also an example section that is only using react-native ( no expo ), with a read me that explains the entire process, from start to finish.

**Comment by midzdotdev** [comment]
Expo would be fantastic too if possible.

**Comment by skidding** [comment]
So, I will completely revamp the docs as part of the v6 master plan, and it will include better instructions for React Native with and without Expo.

But that said, @midzdotdev what exactly is not clear about using React Cosmos with Expo? I use it in all my projects and it's quiet straightforward.

- You install Cosmos and run the `react-native` command to start it.
- You return the `NativeFixtureLoader` component in the App file instead of your usual root component. As [per docs](https://github.com/react-cosmos/react-cosmos/tree/main/docs#react-native).
- You add a main condition based on `global.__DEV__` to return NativeFixtureLoader in dev and your usual root component otherwise when you build your code (to not include Cosmos in production).

Let me know what else needs clarifying.

**Comment by skidding** [comment]
I've improved the React Native docs and extracted it into a self-contained guide with step-by-step instructions to get started in a blank project. Check it out and let me know if you have any feedback: https://github.com/react-cosmos/react-cosmos/blob/main/docs/reactNative.md.
