### ISSUE TITLE
Can't change webpack.output.publicPath via cosmos.webpack.js

### ISSUE THREAD

**Issue by pablo-mayrgundter** [react-cosmos/react-cosmos#1409]
### What's wrong

I'm trying to configure a local dev cosmos serving to root, but build for prod at a subdir, e.g. at '/cosmos'

However, when I build, I do get a newly generated cosmos-export directory, but the html template is hardcoded to use:
```
<script src="/_playground.js"></script>
```

but it should load be:
```
<script src="/cosmos/_playground.js"></script>
```

### Steps to reproduce

Here's my cosmos.config.json
```
{
  "hot": "true",
  "watchDirs": ["src"],
  "hostname": "0.0.0.0",
  "port": "8080",
  "publicPath": "cosmos",
  "webpack": {
    "configPath": ".cosmos.webpack.js"
  }
}
```

Here's my cosmos.webpack.js (I've tried HtmlWebpackPlugin with no config and with `{template: './cosmos.html'}`, but it is ignored.
```
const HtmlWebpackPlugin = require('html-webpack-plugin')
const path = require('path')


module.exports = {
  mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
  devServer: {
    publicPath: '/',
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 8000,
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/cosmos/',
    filename: 'index.html',
  },
  plugins: [new HtmlWebpackPlugin()],
  module: {
    rules: [
      {
        test: /\.jsx$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-react'],
          },
        },
      },
      {
        test: /\.svg$/i,
        use: ['@svgr/webpack'],
      },
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx', '.svg'],
  },
  optimization: {
    minimize: false
  },
}
```

### User info

react-cosmos: ^5.7.2
webpack: ^5.75.0
node: v16.15.0
Mac M1

**Comment by skidding** [comment]
You need to use the `publicUrl` Cosmos setting because the webpack plugin uses it to override the user's `output.publicPath` webpack config. You should be able to set it to `"/cosmos/"`.

https://github.com/react-cosmos/react-cosmos/blob/db571536411cc517ed59e1e8f08747f7b1a89608/packages/react-cosmos-plugin-webpack/src/server/webpackConfig/getDevWebpackConfig.ts#L60-L69

https://github.com/react-cosmos/react-cosmos/blob/db571536411cc517ed59e1e8f08747f7b1a89608/packages/react-cosmos/config.schema.json#L39-L42

**Comment by pablo-mayrgundter** [comment]
Got this working.  Thanks!
