### ISSUE TITLE
Props tab show nothing when decorator for fixture not include `children` in response

### ISSUE THREAD

**Issue by lr0pb** [react-cosmos/react-cosmos#1468]
### What's wrong?

When decorator component does not include `children` in the output, `Props` tab does not show anything

### Steps to reproduce

1.  Create fixture that return *something*, i.e. `() => <h1>Cosmos</h1>`
2.  Create decorator that return *something*, but not `children`, i.e. `() => <h1>Hello</h1>`
3.  See that `Props` tab doesn't show anything

### Screenshots

When `children` is there, `Props` tab exists too:

![изображение](https://user-images.githubusercontent.com/53260102/234968054-31a93e03-6aad-43df-9912-f54246eb16d9.png)

When no `children`, no `Props` tab:

![изображение](https://user-images.githubusercontent.com/53260102/234967649-7cab90a5-d37e-45b9-b84b-ab9c1461e1f1.png)

### User info

- Server terminal output: `[Cosmos] Generated .cosmos\cosmos.imports.ts`
- Browser console output: empty
- Cosmos version: `6.0.0-alpha.17`
- Cosmos config:
```json
{
  "port": 5000,
  "rendererUrl": "http://localhost:5050",
  "exposeImports": ".cosmos/cosmos.imports.ts",
}
```

### Additional context

I use Parcel v2.8.3 as renderer

**Comment by skidding** [comment]
A couple of notes:

- Props panel only shows when at least one set of props are collected from fixture elements.
- Cosmos does not pick up decorator props in both of your examples. When you're returning the fixture you see in the props panel an `<h1>` with `children: Cosmos`, which comes from the fixture, not the decorator.
- Cosmos can only pick up props from fixtures that return the React Elements directly. If you have a function fixture (eg. `export default () => <h1>Cosmos</h1>` you'll see props aren't shown in panel. But in this case it works: `export default <h1>Cosmos</h1>`.
- So in effect Cosmos will never pick up props from decorators unfortunately, because they are always a function (because they need to receive `children` as props to render the selected fixture).

_That said..._ :), there is a lower level primitive you could use if you want to capture decorator props. It's called `FixtureCapture` and I've only exported it in [this PR](https://github.com/react-cosmos/react-cosmos/pull/1469) just now. So if you want to use it make sure to install `react-cosmos@canary`.

```tsx
// cosmos.decorator.tsx
import { FixtureCapture } from 'react-cosmos-core';

export default ({ children }: { children: ReactNode }) => (
  <>
    <FixtureCapture decoratorId="myDecorator">
      <h1 className="hmm">decorator</h1>
    </FixtureCapture>
    {children}
  </>
);
```

You'll notice both `className` and `children` props show up from decorator `<h1>` element, even if you remove the `{children}` fixture element.

But you have to do it explicitly and `FixtureCapture` hasn't really been tested for public use. Might work just fine because it's used internally to pick up fixture props but note that you need to specify a unique decoratorId for its place in the panel UI.

You can choose if this is favorable over using `useValue` / `useSelect` in your decorators.

**Comment by lr0pb** [comment]
Thanks for the response! I understand, that Cosmos does not pick up decorator's props, and it's well, but the issue is, when decorator does not include in returned component `children` (fixture itself), Props tab just doesn't show anything.
This is probably pretty strange, that decorator doesn't return fixture directly, but I run into this issue initially, when I write decorator for [Pixi.js React](https://github.com/pixijs/pixi-react) app.
> Pixi is a rich 2D graphics js renderer
Fixtures return valid React nodes, and Cosmos catch their props well, while there is no specific decorators. But then decorator with Pixi React `<Stage>` component is added. It wrap returned fixture into `<canvas>` element for Pixi to render app. Problem is, that as I explored today, internally, this component return only `<canvas>` element, `children` is being used in other way to call paint on canvas.
So, I still *will* to see the fixture props, however the decorator ain't return fixture directly.
It's probably may be better, if I write this initially, but I thought the issue was wider - just now showing props for fixture, that was *stealed* by decorator and not included *directly* in the response

**Comment by skidding** [comment]
> Fixtures return valid React nodes, and Cosmos catch their props well, while there is no specific decorators around. But then a decorator with Pixi React `<Stage>` component is added. It wraps returned fixture into `<canvas>` element for Pixi to render app. Problem is, that as I explored today, internally, this component return only `<canvas>` element, `children` is being used in other way to call paint on canvas.
So, I still *will* to see the fixture props, however the decorator doesn't return fixture directly.
It's probably may be better, if I write this initially, but I thought the issue was wider - just not showing props for fixture, that was *stealed* by decorator and not included *directly* in the response 

This is odd. If the fixture returns the element directly [the element is wrapped in `FixtureCapture`](https://github.com/react-cosmos/react-cosmos/blob/0f348ba1f0f9cde9afb561f678bbd74828c72f9f/packages/react-cosmos-core/src/renderer/getDecoratedFixtureElement/index.tsx#L16-L18) which connects props to Cosmos UI when it is rendered regardless of decorator. Maybe the Pixi decorator does some magic that changes/clones React elements and something is lost along the way.

Another way you can try to work around this is to use `useValue`:

```tsx
// Example.fixture.tsx
import { useValue } from 'react-cosmos-core';

export default () => {
  const [props] = useValue<MyComponentProps>('myComponentProps', {
    defaultValue: {
      prop1: 'foo',
      prop2: 'bar',
      // ...
    },
  });
  return <MyComponent {...props} />;
};
```

Not as clean but I'd be curious if this works.

**Comment by lr0pb** [comment]
Tried this approach today, it *works*...

![изображение](https://user-images.githubusercontent.com/53260102/235865418-032a7117-746d-40b0-8b88-c18bc448da2d.png)
Fixture in Cosmos

![изображение](https://user-images.githubusercontent.com/53260102/235865020-021441bf-19ae-4d1e-ad59-89a1f2eb533d.png)
Fixture code

![изображение](https://user-images.githubusercontent.com/53260102/235865315-ff2f0568-dca1-4057-b08d-2dd2b5a66d69.png)
Decorator code

... before I remove `children` prop from decorator's response:

![изображение](https://user-images.githubusercontent.com/53260102/235865669-ff1e7436-9136-4a95-9958-8cb3808df87e.png)
Decorator code

![изображение](https://user-images.githubusercontent.com/53260102/235865732-14e93823-18ff-47ed-b41c-3e11ca2d8545.png)
Fixture in Cosmos

So, this is exactly what Pixi React's `Stage` component do, if it being used in the decorator: it return only `<canvas>` element, not including `children` prop directly in this response

So the bug is, that Cosmos does not handle fixture's Props or Controls tab in case when decorator around fixture does not return fixture themself in returned component.

**Comment by skidding** [comment]
> So the bug is, that Cosmos does not handle fixture's Props or Controls tab in case when decorator around fixture does not return fixture themself in returned component.

This is the part I don't get.

If the decorator doesn't return the fixture children _there is no fixture_. The only thing left is a div with width, height and backgroundColor. The props/value panel is populated by the fixture, when the fixture renders. If the decorator doesn't return its children the fixture doesn't render — hence no fixture side effects and no element props or values captured.

—

If you want props/values _always_ shown, even when fixture isn't rendered, you may want to put them in the decorator, which in your case would a wrapper around Pixi's Stage component I guess.

Then the problem becomes how do you read those values inside your fixture. A simple Context should do the trick. You put the Provider in the decorator and read those values with useContext in fixtures (or even inside the components themselves).

This way you get a consistent props/values panel regardless whether or not fixtures are rendered.

**Comment by lr0pb** [comment]
Well, all of this context and other solutions looks a bit like overengeneering on users part. Returning to bug itself, I think, it falls into the next situation:
```tsx
// cosmos.decorator.ts
import { Wrapper } from 'library';

export default ({ children }) => {
  return (
    <Wrapper>{children}</Wrapper>
  );
}
```
I use a valid code in Cosmos' decorator, everything should work.
But there goes the `library` part, as in my case Pixi - for a reason it's `Wrapper` component steal the actual fixture and do with it whatever else to render in their way.
As a `library` user, I don't know exactly what the secret sauce used inside `Wrapper` with that `children` prop, but it renders as expected.
But as a Cosmos user, I dont get anything to understand where is the Props tab gone.
I see there are couple solutions:
- showing on Props tab placeholder similar to `Fixture has no props` but with text like `Your decorator is not returing any fixture`
- add support by default for Props & Controls tabs even when their decorators don't return the fixture
- add support to opt in this "Forced Props & Controls" tab feature

**Comment by skidding** [comment]
> I use a valid code in Cosmos' decorator, everything should work.

Sorry but that's just not the Cosmos props panel works. I tried to explain but I think we reached a dead end. I'll give it one last shot just in case it helps:

Cosmos doesn't read your source code. It intercepts React elements at run time. If the elements are not rendered, there is nothing to show. No other knowledge exists to the Cosmos runtime with regards to the props panel.

With this design it's impossible to know something like:
> - Your decorator is not returning any fixture

And with this design this is also impossible:

> - add support by default for Props & Controls tabs even when their decorators don't return the fixture
> - add support to opt in this "Forced Props & Controls" tab feature

Not saying it's the best design but that's how it works. I wish it could work for your use case but I've already proposed the workarounds I could think of.

Feel free to propose new Cosmos functionality [here](https://github.com/react-cosmos/rfcs). Thanks!
