### ISSUE TITLE
Relay-ification

### ISSUE THREAD

**Issue by KyleAMathews** [react-cosmos/react-cosmos#151]
With Relay and the brave new world of colocated component query fragments, I was thinking Cosmos could get an interesting Relay extension.

Basically, for many/most Relay-ified components, a Cosmo fixture wouldn't be necessary. Instead you could wire it directly to your GraphQL endpoint and use live production data.

What would be fun/useful is if by default, Cosmo would load a random entity to populate the component. This would be a real-world stress test for components you're developing/tweaking.

Even cooler is if there was a button that would trigger a new fetch of a random entity. With that you could quickly toggle through live production data and see how your component responds to each. I'd want a list of each component that you'd loaded to maintained so you could quickly toggle back to previous entries as say you found errors in several of them and are cycling through the entities with errors fixing problems.

A stretch goal would be to add an autocomplete field to search (in some flexibly defined way) for entities to view. E.g. when developing a user profile widget, search for specific users by name.

Thoughts?

**Comment by dzannotti** [comment]
+1

**Comment by KyleAMathews** [comment]
Another idea. Be able to star and label particular objects that you could come back to e.g. an entity that's prone to bugginess. These could show up where fixtures are now.

**Comment by KyleAMathews** [comment]
Oooooo... and what if could create a grid wall of components. Say assign each component to a 100x200 space and each one pulling in a random entity. Or test a component's responsive design by doing some sort of masonary-style layout where components are assigned random heights and widths (well... random within defined constraints). On a large screen you could have dozens or even hundreds of instances of a component loaded that you're hot-reload editing code and styles. That'd be pretty epic. Something with sliders like I'm doing on my demo here: http://kyleamathews.github.io/react-component-gallery/

**Comment by skidding** [comment]
> With Relay and the brave new world of colocated component query fragments, I was thinking Cosmos could get an interesting Relay extension...

I like the Relay extension. Note that an advantage of the component playground is the offline/isolated dev env. Still, having both offline fixtures and the option to hook up to Relay endpoints would be double useful.

That being said, the easiest way to add this extension at the moment would be in [the lib that generates the function tree for ComponentPlayground](https://github.com/skidding/cosmos/blob/60bc9fa893b79cbb404e0b028916a4ec8aa09287/component-playground/lib/get-component-fixture-tree.js). There's already a [PR](https://github.com/skidding/cosmos/pull/136) to automatically generate an empty fixture if no fixtures are found for a component. So the trend to make previously defined fixtures optional is already emerging!

Then there's the [user config](https://github.com/skidding/cosmos/blob/60bc9fa893b79cbb404e0b028916a4ec8aa09287/component-playground/config.js#L19-L20) that we could extend for broader use.

> Another idea. Be able to star and label particular objects that you could come back to e.g. an entity that's prone to bugginess. These could show up where fixtures are now. Store this information in a dot directory in the user's home directory...

I like the concept of fixtures as "bookmarks" as well. But this could be a later stage, right now it's pretty easy to fire up the editor, copy the current props+state and create a fixture file out of it.

> Oooooo... and what if could create a grid wall of component instances. Say assign each component to a 100x200 space and each one pulling in a random entity...

As for the grid, I can +1 that it's a real need. Especially for designer-types and CSS development. Not sure about the resizing, since you could do that via browser resize or dev tools viewport emulation, but viewing more states of the same component at the same time is gold.

I see this as a different component alongside ComponentPlayground, (e.g. ComponentGrid). Then Cosmos could just integrate it and have more bin commands like `node_modules/.bin/component-playground`. The goal of the Cosmos project is to make UI development easier through component design and encapsulation. Sky is the limit :)

Good stuff!

**Comment by KyleAMathews** [comment]
>Not sure about the resizing, since you could do that via browser resize or dev tools viewport emulation

Agreed actually. Most components are responsive based on page width. I was thinking the slider as I have some that keep track of their own width using https://github.com/KyleAMathews/react-component-width-mixin so would render differently if they were full-width for example or if there were two or three in a row. This is easy to setup though so no need to build it into Cosmos.

**Comment by KyleAMathews** [comment]
And glad you like the proposal :) I'm at least several weeks (more likely a month+) from needing this so don't expect a PR from me anytime soon. If anyone wants to pick this idea up and run with it in the meantime, I'd be happy to help out in a limited fashion.

**Comment by skidding** [comment]
I'd love it if @KyleAMathews or somebody else revived this thread, but I'm 2y old so I'm closing it for now.
