### ISSUE TITLE
contextTypes

### ISSUE THREAD

**Issue by Diokuz** [react-cosmos/react-cosmos#185]
My react components uses contextTypes. How to define them in fixtures?

**Comment by skidding** [comment]
Cosmos doesn't work with context at the moment. It was a design decision actually, as context wasn't (not sure if it got in the meantime) documented. You'd have to alter the boilerplate a bit to make it working, but I never had to so far as I avoided using context in all my projects.

**Comment by Diokuz** [comment]
Well, then you do not support many redux and most of fluxible react components :)

Docs is here https://facebook.github.io/react/docs/context.html

**Comment by skidding** [comment]
Update: This can be solved now using Proxies. So far we only have a Redux-specific Proxy created, but we could create a generic Context Proxy to cover custom context scenarios (like themes). I'll document the steps here in case someone wants to contribute any make this happen.

The Proxy would look similar to the [Redux Proxy](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos-redux-proxy/src/index.jsx), but much simpler because there's no subscribing to any changes and no store is involved. Here's a solution abstract (didn't test it):

```jsx
import React from 'react';

const defaults = {
  fixtureKey: 'context',
};

export default function createContextProxy(options) {
  const {
    fixtureKey,
    childContextTypes,
  } = { ...defaults, ...options };

  class ContextProxy extends React.Component {
    getChildContext() {
      return this.props.fixture[fixtureKey] || {};
    }

    render() {
      const {
        nextProxy,
        fixture,
        onPreviewRef,
      } = this.props;

      return React.createElement(nextProxy.value, { ...this.props,
        nextProxy: nextProxy.next(),
        fixture,
        onPreviewRef,
      });
    }
  }

  ContextProxy.propTypes = {
    // ... usual proxy prop types
  };

  ContextProxy.childContextTypes = childContextTypes;

  return ContextProxy;
}
```

The only drawback is that `childContextTypes` must be defined to specify all context types that will be used in all fixtures combined. E.g. 
```js
createContextProxy({
  childContextTypes: {
    color: React.PropTypes.string,
    backgroundColor: React.PropTypes.string,
  }
})
```

**Comment by skidding** [comment]
A generic context proxy has been added in #239 and released under `react-cosmos-context-proxy2.0.0-beta2`.

An [example](https://github.com/react-cosmos/react-cosmos/tree/4498d094117b42c24849bb703a84b2e6f8769dc8/examples/context) has also been added.

Let me know if you try it out and/or have any problems with it. Thanks!
