### ISSUE TITLE
Backend mock middleware

### ISSUE THREAD

**Issue by ovidiubute** [react-cosmos/react-cosmos#253]
### Problem
- If you have a component based on Redux and, for example, your component contains a Button that when clicked it triggers a Redux action that performs a backend request,
- Then you cannot reliably use the Playground to test your component
- Two scenarios will happen:
  - Either your code contains checks for a network error and your component is fine
  - Or not 😢 

### Proposed Solution
- Introduce a `mock-backend` middleware (proxy in `react-cosmos` terms)
- Write what you need inside the fixture, I'm thinking something very close to [`superagent-mock`](https://github.com/M6Web/superagent-mock#usage)
- When Playground starts, it starts a mock server, that serves the data configured in the fixture

### Issues
- User code would need to be configurable to perform the network requests towards Playground (i.e. no hard-coded hostnames, no authentication, and be able to perform requests locally)
- Adds complexity to the fixture

**Comment by skidding** [comment]
How do you see this mock server compared to mocking requests on the client-side, before being sent to the server?

My take:
Pros:
- It works the same regardless of the API used to fetch/send data (XMLHttpRequest or fetch).
- It's decoupled from the client and resembles real life scenarios better.

Cons:
- Hard to create as a Proxy (part of the run time), because it needs to be integrated in the server. Either we extend the Proxy API or add this functionality into the Cosmos server directly.
- There's already an `xhr-proxy` inside web-ui (created together with @RadValentin and @flaviusone) that can serve as a starting point. Maybe it can easily be ported for the `fetch` API as well.
- The `xhr-proxy` took <30min to write (working prototype, no tests). I think the server approach is more complex.

**Comment by ovidiu-bute-hs** [comment]
Didn't know about the `xhr-proxy`. It looks really good, and has the advantage of being pure JavaScript as opposed to a DSL like in my example. I agree the backend way is more difficult to do, and for the end user I think it would be about the same experience, as he still needs to write his fixtures (and add the proxy to his `webpack.config.js` but if we make the API friendly then that will be a no-brainer.

We should open-source the `xhr-proxy` and see about writing a `fetch` one too.

**Comment by skidding** [comment]
> We should open-source the xhr-proxy and see about writing a fetch one too.

Feel free to publish it, I can provide feedback to make it pretty. I wrote it directly on @RadValentin's laptop so I don't have the code myself. :D
