### ISSUE TITLE
Is there more to the home button that I'm not seeing?

### ISSUE THREAD

**Issue by jlc467** [react-cosmos/react-cosmos#264]
First of all, thank you for this great project! Can't wait to start using it more. One thing I can't get off my mind though...As far as I can tell, this is just a home button:
![screen shot 2017-01-22 at 4 20 49 pm](https://cloud.githubusercontent.com/assets/6405557/22186157/37b3e9ac-e0bf-11e6-9b2e-4152fa781efa.png)

I'm trying to understand if it is intended to do more though, given the animated electron and 'play' icon. The behavior of the button doesn't seem to match the UI design. The only thing it does is clear all the query strings in the url, correct? Thanks.

**Comment by skidding** [comment]
Correct, the button only clears the route. The idea was to have something like a logo that's also a home button. The "play" icon because the UI is a component *playground* and the electron because React's logo is an atom.

Feel free to come up with ideas. Maybe the electron could stop when you're on the index page and rotate when a fixture is selected?

Glad to hear you like Cosmos! FYI a new major version is in the making (currently `v2.0.0-beta.4`) and it'll be even better.
