### ISSUE TITLE
how to deploy playground?

### ISSUE THREAD

**Issue by jlc467** [react-cosmos/react-cosmos#283]
### What's up?

Want to achieve playground deployment like https://github.com/react-cosmos/react-cosmos.github.io

### Mkay, tell me more...

I'm using the default webpack config. I don't see any options for writing a bundle so i can deploy.

**Comment by skidding** [comment]
There's no official API for it at the moment. I changed the source code of react-cosmos-webpack on my machine to save the bundle on disk instead of memory to create that export. Are you interested in playing with the source code (maybe even contribute) to achieve this? I can provide pointers to the minimum changes required and how to run a local copy of Cosmos on your codebase. Otherwise I'll keep this open as a feature request until somebody has the time to implement it properly.

**Comment by jlc467** [comment]
> Are you interested in playing with the source code (maybe even contribute) to achieve this?

Sure. Any pointers are appreciated. I have the react-cosmos repo up and running locally. I added a view source button [here](https://github.com/jlc467/react-cosmos/pull/2), but it only really shines when you deploy the playground for viewing when the source isn't on your local.
![screen shot 2017-02-04 at 2 48 39 pm](https://cloud.githubusercontent.com/assets/6405557/22621112/cf36ecaa-eae9-11e6-9131-98a7a82aa720.png)

My end goal is to use react-cosmos as more of a code notebook and less as a component testing solution.

**Comment by skidding** [comment]
I just read your PR, very cool! Are you planning to support code changes as well in the source editor?

Will come back with instructions. 💨

**Comment by skidding** [comment]
The code that bundles webpack (currently into memory via webpack dev middleware) is inside [server.js](https://github.com/react-cosmos/react-cosmos/blob/ed8ef3e09645cd69d0086339ea6e169294bd4aef/packages/react-cosmos-webpack/src/server.js). Right off the bat, I'd start by duplicating this file into something like `export.js`

Inside export.js, you can get rid of webpack-dev-middleware, webpack-hot-middleware and express stuff, since you're not going to start any server.

This is the key part that you want to preserve (among other path-related logic):

```js
const cosmosWebpackConfig = getWebpackConfig(userWebpackConfig, cosmosConfigPath);
const compiler = webpack(cosmosWebpackConfig);
```

Now, instead of passing that `compiler` instance to the dev middleware, you [run](https://webpack.js.org/api/node/#run) it:

```js
compiler.run((err, stats) => {
  // ...
});
```

Except, the webpack config needs a tweak as well. Right now the `publicPath` is set to `/` and the reason for that is explained in the [source comments](https://github.com/react-cosmos/react-cosmos/blob/ed8ef3e09645cd69d0086339ea6e169294bd4aef/packages/react-cosmos-webpack/src/webpack-config.js#L35-L37). The easiest way to solve this (maybe not the most elegant so let me know if you can't think of anything else) is to add a 3rd (optional) `outputPath` param to `getWebpackConfig`. This way you could change the highlighted code to

```js
path: outputPath || '/',
```
This means you'd have to come up with `outputPath` inside `export.js`, and ideally it could be an additional react-cosmos-config option, say `exportPath`, that defaults to something like `join(dirname(cosmosConfigPath), '.cosmos')`.

At this point you have the proper webpack config compiled and ran to save the bundle on disk. A couple of additional tasks that the export operation needs to do:

- Copy `static/index.html` and `static/favicon.ico` in your export path.
- If `publicPath` option is set, copy all static files to `EXPORT_PATH/loader/`

The contents of the export would looks something like this at this point:

```
/path/to/project/cosmos.config.js
/path/to/project/.export/index.html
/path/to/project/.export/favicon.ico
/path/to/project/.export/loader/bundle.js
/path/to/project/.export/loader/some-user-asset.svg
```

I can't guarantee I didn't miss anything as I just ran this in my head, but I think it should give you a good head start and I'm here if you bump into any roadblocks.

**Comment by jlc467** [comment]
Thanks for the instructions! Going to try this right now.

Re: the view source button -- not planning on adding code editing to it. I will use the fixtures editor for playing with components, but beyond that I would miss my code editor too much. I have been dreaming of extending the search box to include searching the source code. Not fuzzy searching, but more like how editors implement find in files. The overall dream is to have a place where you keep code experiments, examples, recipes, or whatever you want. Cosmos auto-discovery and zero-config makes it an ideal solution for this 😄

**Comment by jlc467** [comment]
This PR seems to get the job done for me: https://github.com/jlc467/react-cosmos/pull/4

Haven't tested with a custom webpack config yet, but I'm going to do that next with some file loaders and maybe UglifyJS plugin and see how it all works.

Let me know if I can do more to help get this feature merged. I can make further changes as needed.

**Comment by skidding** [comment]
You sure like the number 22 :P

![image](https://cloud.githubusercontent.com/assets/250750/22628857/49367200-ebe4-11e6-9f35-48fbc8ae9fd3.png)

I looked over your PR and it seems functional. Good stuff! There are a couple of remarks I want to make regarding the config handling:
- `outputPath` can be put inside `defaults` config dict as a relative path since it's resolved afterwards
- The extra webpack config options should be self contained inside `getWebpackConfig` function and not have the response mutated inside `export-bundle.js`
- Come to think of it, `getWebpackConfig` should receive an `export` flag to decide whether to set the outputPath and whether to enable hot reloading. This should get rid of the process.env mess.

Also a couple of naming stuff:
- `export-bundle` can be just `export` (we're not exporting anything other than bundles)
- outputPath should default to something like `cosmos-export` or `cosmos-dist` instead of `dist` because dist might already be used inside the user's repo. 

I can give more detailed inline comments, but you'll have to wait 1-2 days for that. I've been working on a [different project](https://github.com/skidding/illustrated-algorithms) for the past hour and my brain is already overloaded. This is what my desk looks like:
![image](https://cloud.githubusercontent.com/assets/250750/22628976/502663b6-ebe6-11e6-86f6-37c4e8f285c4.png)

A couple of other things:
- You should create a PR here instead of your fork
- Tests will need to be updated/added
- It seems you editor is removing trailing newlines from files. Please add them back if you wish to contribute upstream:
 
![image](https://cloud.githubusercontent.com/assets/250750/22629021/42d04ffa-ebe7-11e6-83a5-364922279679.png)
