### ISSUE TITLE
xhr proxy doesn't work. There is no fixture key in fixture object

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#428]
### What's up?

There is a common line in many proxies:

> const mocks = props.fixture[fixtureKey];

However, there is no desired fixture key in fixture object. We need to look the key in fixture props instead. Here is the right way:

> const mocks = props.fixture.props[fixtureKey];

### Mkay, tell me more...

- I found the clue of the issue, when was trying to understand why _xhr_ proxy doesn't work in my environment.
- However, I think, that the majority of proxies look for the fixture key in a wrong way. [Here are the examples of getting fixture props](https://github.com/react-cosmos/react-cosmos/search?utf8=%E2%9C%93&q=props.fixture%5BfixtureKey%5D&type=).
- react-cosmos-normalize-props-proxy replaces the fixture props in a right way. It looks for the key in **fixture props**, not in fixture object explicitly.

**Comment by skidding** [comment]
There's an example using Axios (which uses XHR underneath) [here](https://github.com/react-cosmos/react-cosmos/tree/master/examples/axios), and it seems to work just fine. You need to put the mocks inside `fixture.xhr`, as described [here](https://github.com/react-cosmos/react-cosmos#activation-4).

Can you please share your code? I don't understand what you mean to be honest. I'm confident we'll figure this out if you share your proxy config and fixture.

**Comment by dfedynich** [comment]
Here is how my fixture looks like when we get it in xhr proxy constructor

![image](https://user-images.githubusercontent.com/7403902/30167514-586886ba-93ef-11e7-80c4-fa59b44b5aa4.png)
![image](https://user-images.githubusercontent.com/7403902/30167595-96773262-93ef-11e7-97a0-feb4265b504e.png)


> const mocks = props.fixture[fixtureKey];

return undefined, so xhr-mock will be never setup. 

The fix is read fixtureKey from fxiture properties. Does it make sense?

I use version 2.0.0-beta.23

**Comment by skidding** [comment]
I think this is because you're using `react-cosmos-normalize-props-proxy` – Can you remove it from your project? 

The only requirement is to put props under `fixture.props`, then you never need to use `react-cosmos-normalize-props-proxy` again. It was meant for my previous company where we had hundreds of fixtures and we didn't have time to write a codemod to update all fixtures.

I believe this is where the confusion from #432 comes.

If you look in your screenshot you can see `xhr` is found in `fixture.props.xhr`, when it should be `fixture.xhr`.

Please try this and let me know if it works. If not please share the **source code** of your fixture and proxies config.

**Comment by skidding** [comment]
@dfedynich in light of our recent discussions, is this still a problem?

**Comment by dfedynich** [comment]
Removing `react-cosmos-normalize-props-proxy` fixed the issue. Thanks a lot for the quick resolution.

**Comment by skidding** [comment]
Happy to help! 🙌
