### ISSUE TITLE
Make a good changelog to display project changes to web community

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#429]
### What's up?

It's great practice to have a changelog file to describe the project changes there. It helps the project's users to monitor the changes and download the updated the package when necessary. I think it will be wholesome for this project to have this file because the development is under the progress and sometimes it becomes difficult to get what changes are implemented after the new commits.

### Mkay, tell me more...

- The changelog file can be composed and updated manually using markdown syntax for github
- The alternative way is to generate and keep the changelog up-to-date automatically. [Github changelog generator](https://github.com/skywinder/github-changelog-generator) or [keep a changelog](https://github.com/olivierlacan/keep-a-changelog) are cool tools to achieve this goal in my view.

**Comment by skidding** [comment]
I completely agree. The issue is Cosmos v2 has been under beta for many months, so you could get a beta version bump with breaking changes. We're going to use proper semver once v2 is released (hopefully this month 🤞). I will compose a comprehensive v2 changelog (it's been a year of work) first, and then the following releases will be small and easy to add to changelog–either manually or via a tool like you suggested. I'll keep this issue open until we put this practice into place.

**Comment by skidding** [comment]
I've added [release notes](https://github.com/react-cosmos/react-cosmos/releases) for since 2.0 and will continue to do so for the time being. When the releases will increase in number we should consider automating the process. Note that [Conventional Commits](https://conventionalcommits.org/) already makes it easy to compose the change log at the end of a release.
