### ISSUE TITLE
Add react-cosmos-normalize-props-proxy example

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#432]
### What's up?

The number of proxies is growing. It's important to have short examples for all of them. **react-cosmos-normalize-props-proxy** is a pretty simple, but very useful proxy in my view. A new developer, who wants to use react-cosmos, can have some difficulties looking into the examples of available fixtures. Some of the fixtures have props, others - don't. It's confusing a little bit, according to the fact, that there is no any mentions about **react-cosmos-normalize-props-proxy** in README.md

**Comment by skidding** [comment]
Well `react-cosmos-normalize-props-proxy` is only meant for users using old versions of Cosmos that didn't have time to upgrade to the latest fixture format. I would prefer people not use it because they would depend on deprecated behavior.

To elabore. In the past fixtures were written like this:
```js
{
  A: 1,
  B: 2,
  C: 3
}
```
A, B and C could be props, _or_ magic fields expected by proxies. This was pretty annoying, because if you wanted to have a prop called `state`, or `reduxState`, or `url`, you couldn't, as it conflicted with proxies.

Now you write fixtures like:
```js
{
  props: {
    A: 1,
    B: 2
  },
  C: 3
}
```
And we always know A & B are props, while C is a special field used by proxies. C never reaches the loaded component. In some cases you might only have props, but the convention is totally worth it because it enables a wide array of proxies and it's not error prone like before.

So my question would be, why are you still using `react-cosmos-normalize-props-proxy`?

**Comment by dfedynich** [comment]
I didn't know, that you treat is as an obsolete proxy. I started my acquaintance with react-cosmos by exploring [flatris](https://github.com/skidding/flatris/commit/ebe7e242fcc71f767067aead03c8a4f47da869e6) and [illustrated-algorithms](https://github.com/skidding/illustrated-algorithms/commit/78314aea4696356f4404e31610e87c8e00d1cfe0) this winter. `react-cosmos-normalize-props-proxy` was widely spread there. So, I still continue using it.

After your explanation above, I understand, that this proxy is rudiment and will get rid of it.

**Comment by skidding** [comment]
That's for pointing this out! I should remove it from both those projects to avoid further confusion.

**Comment by skidding** [comment]
[Removed from Illustrated Algorithms](https://github.com/skidding/illustrated-algorithms/pull/29/files) and [removed from Flatris](https://github.com/skidding/flatris/pull/25/files). Let me know if you still encounter problems.
