### ISSUE TITLE
Cannot find module 'cosmos.config.js'

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#435]
### What's up?

Here the steps to reproduce:
1. Clone [illustrated-algorithms ](https://github.com/skidding/illustrated-algorithms) project 
2. Make the next changes in package.json
    "react-cosmos-context-proxy": "2.0.0-beta.23",
    "react-cosmos-normalize-props-proxy": "2.0.0-beta.23",
    "react-cosmos-telescope": "2.0.0-beta.23",
    "react-cosmos-webpack": "2.0.0-beta.23"

These changes are required because there is a known syntax error issue #434  starting from 2.0.0-beta.24 for NodeJs version 5.
3. npm install
4. npm run cosmos

Actual result is 

![image](https://user-images.githubusercontent.com/7403902/30204625-c66d6b90-948e-11e7-9fb4-f1f0653f377e.png)

- node version 5.12.0
- npm version 3.8.6
- OS Windows 8

### Mkay, tell me more...

I tried to investigate the issue but didn't manage to make it out. It's interesting to note, that the first time, when I run cosmos was the February of 2017. I worked with the obsolete 5th version of NodeJs (yes, I know, that the latest version is 8, but there are heavy reasons, why I still need to stick to version 5). And there was no this issue. Everything worked as expected. Some days ago I update NodeJs to the latest 5 version (5.12.0). After that, I started to get this issue. I thought, that it was because of the NodeJS version. But when reverted back to my previous version of NodeJs the issue didn't disappear.  My colleagues are having the same issue right now (I asked them to check to be sure, that the reason is not in my own environment). I tried to delete node_modules, global npm packages, reinstall NodeJS and NPM, clear npm cache, but nothing helped. 

However, if we change npm script to `cosmos --config ../../../cosmos/cosmos.config.js`, the module will be found. It seems, that working folder becomes `node_modules/react-cosmos-webpack/lib`, but it seems, that it was `illustrated-algorithms` earlier. However, this fix doesn't help, because there are other issues with relative paths.

Could you try to reproduce the issue in your own environment of share some thoughts about the issue?

**Comment by skidding** [comment]
The latest versions are not backwards compatible with `2.0.0-beta.23`. So instead of going back to 23, please upgrade to 27. I just pushed a [patch](https://github.com/react-cosmos/react-cosmos/pull/436/files) to fix #434 and published `2.0.0-beta.27`.

A few notes:
- The reason why we're not running Cosmos tests on Node 5 is because Jest doesn't work on Node 5. It's a long story but you need to pass Node 5 the `--harmony-proxies` flag to work, but this flag no longer exists in newer Node versions so it becomes complicated to maintain support.
- The Contributing Guide actually [mentions](https://github.com/react-cosmos/react-cosmos/blob/master/CONTRIBUTING.md#get-familiar-with-codebase) Node 6+ is required for Cosmos development
- If you want to contribute to Cosmos, I advice using [nvm](https://github.com/creationix/nvm) to switch between Node version.
- Already [upgraded Illustrated Algorithms](https://github.com/skidding/illustrated-algorithms/commit/3d0a5a2e621a3f0649042387d15677d5dcb05179) to 2.0.0-beta.27

Reopen if you still encounter problems.
