### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by mbohgard** [react-cosmos/react-cosmos#486]
I can't find anything at all how to integrate with a codebase running TypeScript and components written in TS (.tsx). Any suggestions?

**Comment by skidding** [comment]
@mbohgard if you already have the Babel loaders set up for TS it might work out of the box. Actually, what extension would you give your fixture files, plain `.js` or `.ts` / `.tsx`?

**Comment by mbohgard** [comment]
Right now, for fixtures, it's not too important. Is it possible to use other extensions for fixtures than .js?

About getting it to work with with our current config, I just get a
```
GET http://localhost:8989/loader/index.html 404 (Not Found)
```
in the console and only the animated cosmos background's showing up. Here's the config I try to use which worked with React Storybook:
```
const path = require("path");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const translations = require("./translations/src/dplay.json");
const I18nPlugin = require("i18n-webpack-plugin");

module.exports = {
  resolve: {
    extensions: [".ts", ".tsx", ".css", ".svg", ".js", ".jsx"]
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        //        include: path.resolve(__dirname, "../../"),
        loader: "awesome-typescript-loader?transpileOnly=true"
      },
      {
        test: /\.css$/,
        //        include: path.resolve(__dirname, "../../"),
        loaders: [
          "style-loader",
          "css-loader?module&localIdentName=[local]-[hash:base64:3]&importLoaders=1",
          "postcss-loader"
        ]
      }
    ]
  },
  plugins: [
    new I18nPlugin(translations, {
      failOnMissing: true
    })
  ]
};
```

**Comment by skidding** [comment]
> Right now, for fixtures, it's not too important. Is it possible to use other extensions for fixtures than .js?

Yes. But let me know if you get to that point because the documentation now isn't ideal. We're in the progress of releasing 3.0 btw, so you might want to try `react-cosmos-webpack@next`.

> GET http://localhost:8989/loader/index.html 404 (Not Found)

It seems like you need to set up HtmlWebpackPlugin:

1. If you haven't add `html-webpack-plugin` to your dev dependencies.
2. Import it in your config file: `const HtmlWebpackPlugin = require('html-webpack-plugin');`
3. Add it to the list of plugins: `new HtmlWebpackPlugin()`

Let me know if this works.

**Comment by mbohgard** [comment]
Nice, no more error. But Cosmos can't find any components (all components has the .tsx extension). I've added a fixture using the docs as a guide. How do Cosmos find components?

**Comment by skidding** [comment]
Great. We're one step closer!

Cosmos <=2 had unintuitive conf for detecting fixtures. This is one the main things v3 brings. So can you please upgrade to `@next` tag and see if your components/fixtures show up.

Notes:
- In v3 Cosmos detects any fixture file that is under `__fixtures__` folder or named as `*.fixture.js`.
- In v3 you no longer need to add `componentPaths` in cosmos.config
- In v3 fixtures have to include component. Eg.

```js
import Component from './Component.js';

export default {
  component: Component,
  props: {
    foo: 'bar'
  }
}
```

There's a codemod for upgrading old fixtures to this format, but I don't think you need it since you're just creating your first fixtures.

**Comment by mbohgard** [comment]
Ok I see. Actually when I installed Cosmos I got the 3.0 beta 3. Now I'm running next and I now understand why I get a
```
Using `componentPaths` config is deprecated. Please consider upgrading.
```
when starting Cosmos. All my components are in a package outside of the Cosmos package (this is a Lerna repo and Cosmos integration is it's own package). So, when I thought I needed the `componentPaths` setting I set the value: `["../common-components/components"]`. I guess Cosmos can't detect components outside of it's own folder?

So, I'm running "@next" version and have the component imported in my fixture. Still no components found though.

**Comment by skidding** [comment]
> All my components are in a package outside of the Cosmos package

Well then, there's a new option in Cosmos 3 called `rootPath`. Can you set its value a directory that's parent to your fixture files?

```js
// cosmos.config.js
module.exports = {
  rootPath: '../' // Go up as many levels as you need
}
```

Warning: All other relative paths from cosmos.config will be relative to rootPath!

--

This is great because my current task is to write the docs for Cosmos 3 😅

**Comment by mbohgard** [comment]
Awesome, that did it! Now it's finding the components that have fixtures. 🎉 

Is it possible though, like we talked about, to have fixtures in another extension than .js? Now JSX won't work since my test for React files is `/\.tsx?$/`.

**Comment by skidding** [comment]
Awesome! 🤘

I'd do it but I'm already engaged in a few other PRs for now. If you have the time, open a tiny PR updating the [following lines](https://github.com/react-cosmos/react-cosmos/blob/8948dbc18bcad1c526056f35251d5c49c0458c6e/packages/react-cosmos-voyager2/src/server/find-fixture-files.js#L20-L21) to something like:

```js
const defaultFileMatch = [
  '**/__fixture?(s)__/**/*.{js,jsx,ts,tsx}',
  '**/?(*.)fixture?(s).{js,jsx,ts,tsx}'
];
```

And I'll gladly merge it and publish `3.0.0-beta.4`with it immediately.

No tests are needed because this is just a default value and current tests will ensure nothing's broken.

Edit: OH, actually you can just set those values in your config under the `fileMatch` option. But I was kinda hoping we make this the default value to work out of the box for other TS users. Nobody wants to write those strings by hand 😁

**Comment by mbohgard** [comment]
Absolutely, I'll open a PR with the fix :)

Thanks for the quick help Ovidiu! Looking forward to start converting Storybook stories to fixtures 😋

**Comment by skidding** [comment]
🎼🎶👂👂

You're welcome @mbohgard. Let me know if you have any other questions.

**Comment by skidding** [comment]
> Also if cosmos.config.js is renamed to cosmos.config.ts, it fails to recognise it.

The cosmos config is read on the server side and isn't processed by webpack loaders. It needs to be Node compatible, similar to `webpack.config.js`.

> Was this done? I get

Not sure that has anything to do with Cosmos, which relies on the user's webpack and Babel configuration. But if you can provide a reproducing repo I'll gladly inspect it.
