### ISSUE TITLE
Make `fixturesDir` work again with new filesystem API and `fileMatch`

### ISSUE THREAD

**Issue by alp82** [react-cosmos/react-cosmos#488]
### What's up?

The new filesystem API allows to change `fileMatch` to search for fixtures at arbitrary locations, which is awesome. But that currently deprecates `fixturesDir` which is sad in my opinion.

### Mkay, tell me more...

Here is the default definition of `fileMatch`: https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-voyager2/src/server/find-fixture-files.js#L20-L21

I think this could use a placeholder for <fixturesDir> or <fixturesName> which gets replace when the respective config property is set. That allows people to easily change fixtures folder names without recreating the whole glob schema.

If someone overwrites `fileMatch`, `fixturesDir` settings will naturally be ignored.

Does that make sense?

**Comment by skidding** [comment]
Approved. Also *free for all* since @alp82 nor me have the time to work on this at the moment.

Just to add more context, the new default value for `fileMatch` would look like this:

```js
[
  '**/<fixturesDir>/**/*.{js,jsx,ts,tsx}',
  '**/?(*.)fixture?(s).{js,jsx,ts,tsx}'
]
```

Also notable, for this improvement I would change the [findFixtureFiles](https://github.com/react-cosmos/react-cosmos/blob/26a149059f935ed445085a69aa254bccc43c9425/packages/react-cosmos-voyager2/src/server/find-fixture-files.js#L29-L31) args to receive a complete `cosmosConfig` object. This way it would have access to the new `fixturesDir` and any other config option in the future.

**Comment by alp82** [comment]
We could even go a step further and also introduce a `fixturesSuffix` property to use it in there:

```
[
  '**/<fixturesDir>/**/*.{js,jsx,ts,tsx}',
  '**/?(*.)<fixturesSuffix>.{js,jsx,ts,tsx}'
]
```

**Comment by skidding** [comment]
Good idea. I think keeping them separate is more flexible. So I'm a fan of both `fixtureDir` and `fixtureSuffix` options (just realized singular "fixture" sounds more natural). Even more accurate might be `fixtureFileSuffix`.

**Comment by skidding** [comment]
Both `fixturesDir` and `fixtureFileSuffix` are supported options in Cosmos Next. The defaults are `__fixtures__` and `fixture` respectively.
