### ISSUE TITLE
Prettify component names (extract HoC names)

### ISSUE THREAD

**Issue by alp82** [react-cosmos/react-cosmos#508]
### What's up?
If using HOCs, component names could be percieved as unpleasant due most of them wrap their name around the inner component, e.g. `MyHOC(glamorous(MyComponent))`.

An alternative approach came up as a discussion in https://github.com/react-cosmos/react-cosmos/issues/494#issuecomment-342089653, so that names would be as easy as `MyComponent`, regardless of how many HOCs are wrapped around.

### Mkay, tell me more...

Quote:
> It's annoying to rename all components if you use many HoCs and don't like how the composed names look. There is another possibility. From [this comment](https://github.com/react-cosmos/react-cosmos/issues/495#issuecomment-341994921) you can see we already gather component names statically. Those names are simpler, they are the names we give component imports in our fixtures. We could add a Cosmos config to rely on those instead of run time names. Eg. `preferRuntimeComponentNames` which I'd still keep `true` by default but you might prefer to set to `false`. Note: Component names gathered statically are even more experimental and can be confusing. If you do `import MyComponent from './ActualComponentName.jsx'` it will show up as `MyComponent` in the UI.

**Comment by alp82** [comment]
solved with beta12?

**Comment by skidding** [comment]
I think a more accurate name would be "Option to prefer static vs dynamic component names". We already have both data btw, but we don't have a way to switch between them and always prefer using dynamic component names.

While I'm perfectly OK with having this option available, I think there's a lot more potential in formatting the dynamic name, because it's rich in information.

Eg. `connect(glamorous(withRouter(Menu)))` is an ugly name, but it tells a lot. If we become aware of the `HoC(x)` convention we can extract the component name and list of wrapping higher order components. Once we do this, we can show the HoCs with smaller font, under the component, or hidden in an tooltip. Better yet, we can build a list of known HoCs and map stuff like "withRouter" to "React Router" and "connect" to "Redux". I think it's important to know the HoCs that the loaded components is wrapped by. Here's an ugly sketch about it:

![img_20171110_192102](https://user-images.githubusercontent.com/250750/32670556-cc2adc08-c64c-11e7-85e4-c6852f70cf6e.jpg)

**Comment by alp82** [comment]
This is a great idea!

I think showing that information inline might be too cluttered. Tooltip is a good approach. Another possibility would be some place for showing meta information. That could be a header on top of the main content area where the active selection is shown with all wrapping HOCs around it.

**Comment by skidding** [comment]
FYI Renamed this issue towards using the existing names but extracting the HoC names for cleaner names with meta data. I think the initial idea to optionally use the statically extracted component names is inferior and shouldn't be pursued for now. Prettifying the dynamic names provides more value and doesn't introduce another config users have to think about.

Free for all.

**Comment by maxsalven** [comment]
https://github.com/react-cosmos/react-cosmos/pull/523

**Comment by skidding** [comment]
Hey, this is done! 🎊
