### ISSUE TITLE
Read "children" from fixture.props.children

### ISSUE THREAD

**Issue by andreypopp** [react-cosmos/react-cosmos#559]
I understand that placing `children` at the top level of fixture is an optimisation for a common case, I'm talking about:

```
export default {
  component: ...,
  props: { ... },
  children: ...
}
```

I'd argue though that it breaks a symmetry between accessing `children` via `this.props.children` (or `props.children` in functional components) and providing them to the fixture.

That symmetry property which is broken is very important, I think, as it allows a developer with knowledge of React and no knowledge of React Cosmos immediately start to use Cosmos w/o looking at the docs. Instead I was confused by providing `children` in `props` didn't work and had to lookup the docs for that.

Thank you for creating Cosmos!

**Comment by skidding** [comment]
@andreypopp I see your point, and I believe at some point in Cosmos history `children` were read from `fixture.props.children`. But the thing is children *are* special in React. They are the 3rd argument to [React.createElement](https://reactjs.org/docs/react-api.html#createelement), after `type` and `props`. That said, after pausing to dig a bit more on this it [seems](https://twitter.com/dan_abramov/status/933408464671531008) there's no other difference past element creation.

Also, avoiding user confusion is more important than mirroring the React.createElement API that probably few people think of when creating components. So I welcome ideas. We could:
1. Warn on `fixture.props.children` and inform people that they might be looking for `fixture.children`
2. Use either `fixture.props.children` and `fixture.children` as 3rd argument to React.createElement.

But still I have to wonder, what happens when you do `<Component children={<span>YO</span>} />` instead of `<Component><span>YO</span></Component>`? If it's exactly the same then I don't see why we can't go with Option 2.

**Comment by andreypopp** [comment]
Also #560 is probably a requirement to make API typeable.

**Comment by andreypopp** [comment]
> But the thing is children are special in React. They are the 3rd argument to React.createElement, after type and props. That said, after pausing to dig a bit more on this it seems there's no other difference past element creation.

I strongly disagree with that. There are syntactical difference but API symmetry between definition and consumer site is a much stronger invariant and this is what I'm talking about.

**Comment by andreypopp** [comment]
> But still I have to wonder, what happens when you do <Component children={<span>YO</span>} /> instead of <Component><span>YO</span></Component>? 

They are the same for `React`. As I said that's just syntactical sugar. I don't think Cosmos should built an API around that.

**Comment by skidding** [comment]
Happy to accept a PR to use `fixture.props.children` as children. [Here](https://github.com/react-cosmos/react-cosmos/blob/ede293e1239202cb962077fd3157813f181b7861/packages/react-cosmos-loader/src/components/PropsProxy/index.js#L10-L22) is the relevant code. With the mention that `fixture.children` should continue to be supported and not break API for existing users.

**Comment by maxsalven** [comment]
I'd prefer to use the `fixture.props.children` syntax personally.

Here's the relevant source in the React codebase BTW, everything ends up in `props`:
https://github.com/facebook/react/blob/3c977dea6b96f6a9bb39f09886848da870748441/packages/react/src/ReactElement.js#L202

**Comment by skidding** [comment]
OK, after going deeper with typed fixtures it's clear to me that `children` needs to be under `fixture.props` 😬

I'm green lighting this as a free for all task. I'd be great if someone is interested in doing a core yet relatively light contribution to Cosmos.
