### ISSUE TITLE
Fixture editor doesn't preserve collapsed state between updates

### ISSUE THREAD

**Issue by NiGhTTraX** [react-cosmos/react-cosmos#569]
### What's up?

A picture is worth a thousand words. A GIF is worth a thousand words per second:

![fixture-editor-collapsing](https://user-images.githubusercontent.com/485061/34560019-7f584992-f144-11e7-997c-2c200b2fb016.gif)

### Mkay, tell me more...

You can see the collapse arrows blinking in the GIF after every update; I'm guessing it's related.

**Comment by skidding** [comment]
Yeah, it's annoying. It might be possible to read current folded lines and apply them again after a fixture change. See https://codemirror.net/doc/manual.html#addon_foldcode

But I personally won't work on this because I'm planning to design a control panel to replace the fixture editor. Broadly, I want each fixture section to have a separate (collapsable) section with plugin support. Which will gradually transform the JSON blob into custom UI controls for each fixture part.
