### ISSUE TITLE
No documentation on how to use the mount method to group multiple fixture inside the UI

### ISSUE THREAD

**Issue by RPDeshaies** [react-cosmos/react-cosmos#579]
### What's up?

There is no documentation on how to load multiple fixture inside a group when using `react-cosmos-loader`'s `mount()` method 

### Mkay, tell me more...

I'm using react-cosmos with [Fusebox](fuse-box.org) and have a custom implementation so I have to use the `mount()` method inside the `react-cosmos-loader` package.

Considering the following code
```ts
const { mount } = require("react-cosmos-loader");
const someFixture = require("./some-fixture.fixture");

mount({
  proxies: [],
  fixtures: {
    "test": someFixture
  }
});
```

Generate this: 

![image](https://user-images.githubusercontent.com/6224111/35528030-8b9407e0-04fa-11e8-836d-c5028925e643.png)

But how can I have multiple fixture under that group using the API from `mount()` ???

**Comment by RPDeshaies** [comment]
I'ved tried using

```
mount({
  proxies: [],
  fixtures: {
    "test": [someFixture,someFixture,someFixture]
  }
});
```

But it doesn't work so I guess there's something else that needs to be done

**Comment by skidding** [comment]
You need to give each fixture a name:

```js
mount({
  proxies: [],
  fixtures: {
    "ComponentA": {
      "fixtureA": someFixture,
      "fixtureB": someFixture
    },
    "ComponentB": {
      "fixtureA": someFixture,
      "fixtureB": someFixture
    },
    // etc.
  }
});
```

Let me know if this helps.

**Comment by RPDeshaies** [comment]
Hey, @skidding the fixtures are now indeed visible inside the list but when I try to load them, I have errors in my console saying:

```
MyComponent.tsx:16 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at isComponentClass (MyComponent.tsx:16)
    at PropsProxy.render (MyComponent.tsx:16)
    at finishClassComponent (MyComponent.tsx:16)
    at updateClassComponent (MyComponent.tsx:16)
    at beginWork (MyComponent.tsx:16)
    at performUnitOfWork (MyComponent.tsx:16)
    at workLoop (MyComponent.tsx:16)
    at HTMLUnknownElement.callCallback (MyComponent.tsx:16)
    at Object.invokeGuardedCallbackDev (MyComponent.tsx:16)
    at invokeGuardedCallback (MyComponent.tsx:16)
```

And
```
MyComponent.tsx:16 The above error occurred in the <PropsProxy> component:
    in PropsProxy (created by StateProxy)
    in StateProxy (created by ErrorCatchProxy)
    in ErrorCatchProxy (created by Loader)
    in Loader

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorCatchProxy.
```

**Comment by skidding** [comment]
It sounds like your fixtures are ES6 modules so maybe this will work:

```js
mount({
  proxies: [],
  fixtures: {
    "ComponentA": {
      "fixtureA": someFixture.default
    }
  }
});
```

If this works, you can use a helper we use throughout the Cosmos packages to normalize modules at run time:

```
import { importModule } from 'react-cosmos-shared';

mount({
  proxies: [],
  fixtures: {
    "ComponentA": {
      "fixtureA": importModule(someFixture)
    }
  }
});
```

**Comment by RPDeshaies** [comment]
Ok yeah you are right. I didn't know I needed to use this since if I don't provide a name for the fixture, I do not need to call the `default`.

Thanks for all the help.

Any plans on adding that to the doc ?

**Comment by skidding** [comment]
With pleasure!

> Any plans on adding that to the doc ?

Not right now... 

I want to make sure the main APIs are clear enough before adding instructions on how to use the lower level primitives in Cosmos. Kudos for making it work btw, I don't think `react-cosmos-loader` is documented at all at the moment.

On the other hand, I never heard of FuseBox before so if you're interested it might be valuable to create an `examples` folder with a minimal setup extracted from yours.

**Comment by cal0610** [comment]
I've tried using react-cosmos but we couldn't figure it out with the documentation. I really liked what it can provide though!

**Comment by skidding** [comment]
@cal0610 can you tell me what you tried? Maybe I can help

**Comment by cal0610** [comment]
@skidding 

I've got it set up and working on a very very dumb component. I could change the props and state on http://localhost:8989 and see the component changing accordingly.

I've had too many issues within a short period of time and thought it wasn't worth using, here are a few:

1. Creating fixtures requires server restart - would've been nice to know this was the case rather than thinking something was wrong
2. Setting up react-cosmos
I'm using react-boilerplate so I just created cosmos.config.js on project root as per instruction:

// cosmos.config.js
module.exports = {
  containerQuerySelector: '#app',
  webpackConfigPath: './internals/webpack/webpack.dev.babel',
  globalImports: ['./app/global-styles.js']
};

I changed  the application background in global-styles.js and saw the background also change on react-cosmos, great!!

When I tried creating a fixture from my component that uses 3rd party css like blueprint, the css was not applied on cosmos. I then made this change as per documentation:

```
  globalImports: ['./app/global-styles.js', './app/main.scss']
```
but this did not work on cosmos even though my component was styled on localhost:3000/.
I have my css import defined on app.js:
`import '@blueprintjs/core/dist/blueprint.css';`

What I ended up having to do was to add the same import statement in my component just so cosmos picks up the css. 

Not sure what the issue might be, moving on...

3. Followed the enzyme testing as per doc but there are far too few examples to really use it in our project

```
import createTestContext from 'react-cosmos-test/enzyme';
import fixture from './fixture';

const { mount, getWrapper } = createTestContext({ fixture });

beforeEach(mount);

test('renders hello', () => {
  expect(getWrapper().text()).toContain('Hello World');
});
```

Also, I'd like to find out more information about createTestContext, mount, and getWrapper. How is this different from shallow from enzyme? What can you call on getWrapper? How do you check the state from the mounted fixture? As per doc, you can capture state changes through get('reduxState'). Ok...time to set up redux proxy.

4. 

```
// cosmos.proxies.js
import createReduxProxy from 'react-cosmos-redux-proxy';
import configureStore from './configureStore';

const ReduxProxy = createReduxProxy({
  createStore: state => configureStore(state)
});

export default [
  ReduxProxy
  // ...other proxies
];

```

The doc doesn't specify where to place this file, I placed it in project root same as the other config anyway. Next, let's create our fixture with the state from redux. Searching through the docs, this is all I could find:

```
// __fixtures__/example.js
export default {
  component: MyComponent,
  // An empty object will populate the store with the initial state
  // returned by reducers. But we can also put any state we want here.
  reduxState: {}
};
```
I then tried to google examples but didn't find anything that pointed me to anything solid.

:(

**Comment by skidding** [comment]
@cal0610 Oh man, I get it, it's a painful process at first. But I have to say you did pretty well!

> Creating fixtures requires server restart - would've been nice to know this was the case rather than thinking something was wrong

This is something I'm thinking about actively and will address in the near future one way or another. Note that new fixtures for existing components will appear instantly, you need to restart only when you add a new component. Still sucks tho.

> this did not work on cosmos even though my component was styled on localhost:3000/.
I have my css import defined on app.js:

You should be able to add `'@blueprintjs/core/dist/blueprint.css'` to globalImports as well.

> Also, I'd like to find out more information about createTestContext, mount, and getWrapper.  How is this different from shallow from enzyme?

The main diffference is you use Cosmos fixtures instead of JSX to set up your component. With JSX you mock props. With fixtures you mock EVERYTHING (once you figure out the sometimes annoying config of course).

> What can you call on getWrapper?

`createTestContext` will use Enzyme's full rendering. `getWrapper` returns the enzyme wrapper and then you have the Enzyme API. There's some suger on top like `getWrapper(selector)` is equal to `getWrapper().find(selector)`, but that's optional and maybe shouldn't worry at first. The docs could definitely be improved but Cosmos exposes so many APIs and there's not a lot of people working on it, so you have to be a bit patient here. We're slowly getting there...

> The doc doesn't specify where to place this file

Have you seen this?

![image](https://user-images.githubusercontent.com/250750/37762051-eb46b202-2ded-11e8-8fe2-2de48915aad6.png)

> Searching through the docs, this is all I could find:

Well that should be enough to get you started. Once you have the `reduxState` on your fixture and the proxy configured, your component will be automatically wrapped inside the Redux provider and you'll be able to mock any state via `fixture.reduxState`. Check out this [Redux example](https://github.com/react-cosmos/react-cosmos/tree/9ea980161c6ac0b96cbf8f47af86436d2abeb4a0/examples/redux).

---

You're so close, don't leave now! I believe you'll be fully rewarded once you get on the other side :). You might hit other roadbloacks in the future, but you only config the main parts once and then reap the benefits. ✌️

**Comment by cal0610** [comment]
@skidding Thanks !! I appreciate your feedback! I'll give this another crack tomorrow after a coffee.

**Comment by cal0610** [comment]
Hi @skidding 

Thanks for your feedback, I've got it working now :) 

I've found a problem with using redux-saga with this. My component is using like this:
```

const withConnect = connect(null, mapDispatchToProps);
const withSaga = injectSaga({ key: 'home', saga });

export default compose(
  withSaga,
  withConnect,
)(InvoiceCreateForm);

```

And this is the error I get on the console:

> Uncaught ReferenceError: regeneratorRuntime is not defined
>     at eval (saga.js:7)
>     at Object../app/containers/Supplier/InvoiceCreateForm/saga.js (main.js:995)

I don't suppose there is a fix for this is there ? :(

**Comment by cal0610** [comment]
@skidding 

I've failed miserably on testing :(

The example on the documentation does not work for me unfortunately.

This is my component:

```
import React from 'react';

// eslint-disable-next-line react/prop-types
const Status = ({ status, received, created, completionKpi, assignedTo }) => (
  <table>
    <h1>Status</h1>
    <tr>
      <th className="pt-input">Status:</th>
      <th className="pt-tag pt-intent-warning">{status}</th>
    </tr>
    <tr>
      <td className="pt-input">Received:</td>
      <td className="pt-tag">{received}</td>
    </tr>
    <tr>
      <td className="pt-input">Created:</td>
      <td className="pt-tag">{created}</td>
    </tr>
    <tr>
      <td className="pt-input">Completion KPI target:</td>
      <td className="pt-tag">{completionKpi}</td>
    </tr>
    <tr>
      <td className="pt-input">Assigned to:</td>
      <td className="pt-tag">{assignedTo}</td>
    </tr>
  </table>
);

export default Status;

```
This is my test:

```
import React from 'react';
import createTestContext from 'react-cosmos-test/enzyme';
import fixture from '../__fixtures__/index.fixture';

const { mount, getWrapper } = createTestContext({ fixture });

describe('renders correctly', () => {
  beforeEach(mount);

  it('test', () => {
    console.log(getWrapper().text());
    expect(getWrapper().text()).toContain('Status');
  });
});

```

And finally, this is the lovely error I get:

> **TypeError: Cannot read property 'prototype' of undefined**

This component is not connected or anything so I would've expected this to work straight away :(

Thanks in advance~

**Comment by cal0610** [comment]
@skidding - not exactly, sorry .. 


This is my fixture:

```
import Status from '../index';


export default [
  {
    component: Status,
    props: {
      status: 'Completed',
      received: 'No',
      created: '21st March 2018',
      completionKpi: '2 hours',
      assignedTo: 'Calvin',
    },
  },
];

```

**Comment by skidding** [comment]
OH, `createTestContext` doesn't work with fixture arrays because you can't test more fixtures at the same time.

Try this:

```diff
-import fixture from '../__fixtures__/index.fixture';
+import fixtures from '../__fixtures__/index.fixture';

-const { mount, getWrapper } = createTestContext({ fixture });
+const { mount, getWrapper } = createTestContext({ fixture: fixtures[0] });
```

**Comment by cal0610** [comment]
@skidding 

Thank you! That solved the problem.

Now there was no way I could've known that right? ;p

**Comment by skidding** [comment]
> Now there was no way I could've known that right? ;p

You are right. 😅

We need to add a warning message in place for this! 

When `createTestContext` gets called with fixture an array it should say something like

> createContext can't be called with an array of fixtures because you can only test one fixture at a time. If you imported a fixture file that returns an array, pick one fixture from that array to pass to createContext.

And it should probable go [here](https://github.com/react-cosmos/react-cosmos/blob/58bcd54e28a3e151813b9ef49e120a88bb2fbc2f/packages/react-cosmos-loader/src/create-context.js#L40).

If you have some time and want to prevent this from bugging other people in the future, maybe you can add it! 🍻

**Comment by cal0610** [comment]
@skidding 

No problem, I'm keen to help contribute when I get some time :)

Btw, would you mind sharing your config for the saga regenerator runtime on globalImport?

This is what I have right now...:

```
globalImports: [
    './app/global-styles.js',
    './node_modules/@blueprintjs/core/dist/blueprint.css',
    './node_modules/@blueprintjs/datetime/lib/css/blueprint-datetime.css',
    './app/main.scss',
    './node_modules/react-select/dist/react-select.css',
    './node_modules/redux-saga/dist/redux-saga.js',
  ],
```

**Comment by skidding** [comment]
> I need another coffee...

>    **'./node_modules/regenerator-runtime/runtime.js',**

Wouldn't just `'regenerator-runtime/runtime'` work?

Same goes for all your global imports, I'd think `./node_modules/` prefix isn't required since webpack resolves modules to `node_modules` by default.
