### ISSUE TITLE
getRootWrapper().setProps({prop : val})` inside a test does not set props

### ISSUE THREAD

**Issue by mmacaula** [react-cosmos/react-cosmos#581]
### What's up?

Calling `getRootWrapper().setProps({prop : val})` inside a test does not seem to set the props on my component.

### Mkay, tell me more...

I'm testing a redux-form field component, and have a fixture like this:

```
export default {
  component: reduxForm({ form: 'formName' })(MyComponent),
  props: {
    name: 'field',
    isNegative: true,
  },
  reduxState: {},
};
```

and i'm trying to *overwrite a prop from the fixture* during the test, instead of making a whole new fixture with the updated prop.  
```
const { mount, getWrapper, getRootWrapper, get } = createTestContext({ fixture });
beforeEach(mount);
test('changing isNegative should do something', () => {
  getRootWrapper().setProps({ isNegative: false }, () => {
      console.log(getWrapper().props()); // shows isNegative: true
      expect(stuff) // but.fails.because.prop.is.still.true
    });
});
```

Is there a better way to accomplish what i'm trying to do here?

**Comment by skidding** [comment]
Hi @mmacaula,

Setting props on the root wrapper doesn't work because the root wrapper is the Cosmos Loader component. createContext creates a structure like this: `CosmosLoader(ReduxProxy(...otherProxies(YourComponent)))`. Which is why there's a distinction between `getRootWrapper` and `getWrapper.` Actually I don't think getRootWrapper is documented so I'm not sure how you came about it :)

But I'm thinking we should expose a `set({ props: { foo: 'bar' })` method anyway, with an additional `setProps({ foo: 'bar' })` for convenience. But are you interested in re-rendering the component from scratch, or it going through the `componentWillReceiveProps` lifecycle path? The former is fairly easy to do with how Cosmos works today, while the latter requires more work (tho it's still wanted eventually).

**Comment by mmacaula** [comment]
Thank you for the quick and informative reply (as well as your work)!  

I came about `getRootWrapper` by looking through the source... :)  Using `getWrapper` to set props gives me this error message: `ReactWrapper::setProps() can only be called on the root`  from enzyme, which makes sense as an error message based on my knowledge of React. 

> But are you interested in re-rendering the component from scratch, or it going through the componentWillReceiveProps lifecycle path? 

My initial thought for the test was to do the lifecycle path, since my component does respond that way (and theoretically should be tested that way too), but I could use some guidance on the former. 
 Should I just clone my imported fixture with a new set of props, then create a new context and then test from there or is there a simpler way?

**Comment by skidding** [comment]
> Should I just clone my imported fixture with a new set of props, then create a new context and then test from there or is there a simpler way?

Yes, unfortunately there's no simpler way at the moment.

If you're interested in opening an issue for a feature request to add a setProps method to the fixture context, I welcome it gladly. I'm not able to dive into it in the near future, but I'd be happy to guide someone interested in contributing. In any case, I'm sure we'll get to it eventually because it sounds like a popular use case.

**Comment by mmacaula** [comment]
closing this due to workaround found in #583
