### ISSUE TITLE
Using `set` to set reduxState in test context doesn't update the actual st. 

### ISSUE THREAD

**Issue by mmacaula** [react-cosmos/react-cosmos#598]
### What's up?

Setting reduxState in test context doesn't update the actual state. 

### Mkay, tell me more...

Turns out this test from the docs doesn't actually work...  
```
test('responds to new state', () => {
  const newState = { showWarning: true };
  set('reduxState', newState);
  expect(getWrapper('.btn').hasClass('warning')).toBeTruthy();
});
```

This is my bad for not testing it in my other PR the other day.  Once the store has been created in the redux-proxy, it takes over management of the store state (as it should) and doesn't do anything with an updated fixture props.  I tried setting the 'alwaysCreateStore' option on the proxy but that doesn't work (it only does it on the constructor, not componendDidUpdate.  

Now I'm also not sure that the other proxies also respond to the fixture being updated as a lifecycle change and respond accordingly.  

I'm wondering what the best way to go about doing this would be?   Happy to help (since I created a buggy 'feature').

**Comment by skidding** [comment]
Thanks for bringing this up!

One solution would be to call `mount` internally. But this wouldn't work out of the box because [mount](https://github.com/react-cosmos/react-cosmos/blob/c1e047f8f45d83bca1f04959cbab3fb07e575dd3/packages/react-cosmos-loader/src/create-context.js#L75) uses the catched fixture contents (initialized on `createContext` and updated whenever proxies send updates).

Which brings me to the higher issue. `set` should reach the [inner `createContext` abstraction](https://github.com/react-cosmos/react-cosmos/blob/c1e047f8f45d83bca1f04959cbab3fb07e575dd3/packages/react-cosmos-loader/src/create-context.js), which handles the fixture cache and the `mount` method. It would be great if we could do this as it would open a whole number of possibilities. For example if we had `setProps` functionality for the generic `createContext`, which is at the base of the test helpers, but also of the Playground UI, we could later add UI controls in the fixture editor to simulate prop transitions. 

There are three layers of abstraction:

- `import createEnzymeContext from 'react-cosmos-test/enzyme'`
- `import createTestContext from 'react-cosmos-test/generic'`
- `import { createContext } from 'react-cosmos-loader'`

The enzyme context calls the generic test context with the Enzyme renderer, and the generic test context calls the base context with some server side sugar (eg. auto-mocking callbacks in jest environment and file detection for Cosmos proxies).

All core methods should be in the environment-agnostic `createContext`, and we must strive to move `set`, and even `setProps` there.

@mmacaula let me know if this interests you and we can discuss further. It's probably more than you signed up for, but so is the impact. Reading [packages/react-cosmos-loader/src/create-context.js](https://github.com/react-cosmos/react-cosmos/blob/c1e047f8f45d83bca1f04959cbab3fb07e575dd3/packages/react-cosmos-loader/src/create-context.js) (140 brief lines of code) is the best starting point to understand the underlying abstraction.

**Comment by mmacaula** [comment]
Wouldn't calling mount again destroy and re-build the component from scratch with the updated reduxState?   That would work for the UI where you do that all the time but for testing, if i want to test lifecycle methods, I'm not sure it would.  

If we wanted to do lifecycle testing, we'd have to get the redux-proxy to somehow replace the whole store with the passed in state somehow.  Would it be possible to have the redux-proxy implement its own lifecycle method to determine that the fixture prop for reduxState has changed and therefore it should dump the current store, recreate it with the new state and pass that updated state down to child proxies?  Or am I completely missing something?

**Comment by skidding** [comment]
> Wouldn't calling mount again destroy and re-build the component from scratch with the updated reduxState? That would work for the UI where you do that all the time but for testing, if i want to test lifecycle methods, I'm not sure it would.

Not if we call it like `mount(clearPrevInstance = false)`. This way we'd end up following the `componentWillReceiveProps => componentWillUpdate => componentDidUpdate` render path of the Loader and all nested proxies.

> If we wanted to do lifecycle testing, we'd have to get the redux-proxy to somehow replace the whole store with the passed in state somehow. Would it be possible to have the redux-proxy implement its own lifecycle method to determine that the fixture prop for reduxState has changed and therefore it should dump the current store, recreate it with the new state and pass that updated state down to child proxies? Or am I completely missing something?

**Comment by skidding** [comment]
So, to bring back `set` and improve docs:
- Redux proxy needs to "listen" for fixture changes in `componentWillReceiveProps`
- `set` and `setProps` need to be labeled as `Enzyme context-only`, as they aren't available if we `react-test-renderer` or the DOM renderer
- We should specify that these setters need to be implemented in proxies as well to work completely, and possibly add TODOs in other affected proxies

To add `set` and `setProps` to other renderers:
- I don't think `react-test-renderer` allows updating the wrapper, so unless I'm wrong, we should specify that this functionality isn't supported with this renderer
- For the DOM loader, instead of calling `wrapper.setProps` (where wrapper is the Cosmos Loader component), we just need to do update the fixture cache internally and implicitly call `mount(false)`, and since the DOM container is the same the update lifecycle path will be triggered

**Comment by mmacaula** [comment]
I'm working on the redux proxy now (with tests), I'll also try to take a stab at looking through the other renderers and adding TODOs or just fixing them.  Would you prefer smaller PRs for each of those as I find them?

**Comment by skidding** [comment]
> I'm working on the redux proxy now (with tests), I'll also try to take a stab at looking through the other renderers and adding TODOs or just fixing them.

Awesome!

> Would you prefer smaller PRs for each of those as I find them?

Smaller PRs are my preference, but feel free to go with the path you're most comfortable with.

**Comment by mmacaula** [comment]
@skidding Sorry it's been awhile, had some personal things going on...  I got around to implementing the updated redux proxy and all _looks_ good, but it doesn't actually work.  My naive attempt was to just recreate the store with the new state, but that doesn't quite work as the `connect` component grabs the store off context and holds onto it for its lifetime, which makes sense of course, stores don't just get replaced in redux apps.  This means the connected component under test still maintains the reference to the old store and there's not an effective way of updating it. 

SO that means the initial approach won't quite work, and I suspect for some other proxies it won't work either if they use their context value the same way.  

The only other approach I can think of is a bit crazy but will work.  You'll have to tell me if this is worth pursuing.  It basically involves replacing the reducers of the application with one that returns the updated fixture state, dispatching a random action to replace the whole store, then putting the old reducers back.  Something like this:

```
  // redux-proxy code
  componentWillReceiveProps(nextProps) {
      const oldReduxState = this.props.fixture[fixtureKey];
      const newReduxState = nextProps.fixture[fixtureKey];
      if (oldReduxState !== newReduxState && options.reducers) { // options.reducers is key 
        this.reloadStore(nextProps);
      }
    }

    reloadStore(props) {
      const fixtureReduxState = props.fixture[fixtureKey];
      this.store.replaceReducer(() => fixtureReduxState);  // a reducer that replaces the state with new fixture state
      this.store.dispatch({type: '@@react-cosmos-replace'});  // dispatch random action to run reducer
      this.store.replaceReducer(options.reducers);  // put old reducer back 
    }

``` 

This approach requires that if users want to be able to set (or update) the state, they need to provide as an extra option their `reducers` (or first argument of `createStore`) to the proxy.  Otherwise its just not possible as far as I can tell.  I was able to do this in my project's code base by exporting the reducers alongside the `configureStore` function.

Thoughts?  It's a bit hacky but I'm not sure of another way.

**Comment by skidding** [comment]
> My naive attempt was to just recreate the store with the new state, but that doesn't quite work as the connect component grabs the store off context and holds onto it for its lifetime

How about invalidating the entire child tree by setting an incremental `key` to the next proxy?

In short:
- `state = { storeId: 0 }` on the ReduxProxy component class
- `React.createElement(nextProxy.value, { key: this.state.storeId, ...` in render
- ` componentDidReceiveProps(nextProps) { if (oldReduxState !== newReduxState) { this.setState({ storeId: this.state.storeId + 1 })...` (Wondering if we need to do shallow or deep comparison here, but we can worry about that later)

Would this work?

**Comment by mmacaula** [comment]
Yep that works!  At least in my use case.  Do you think it'll work in all cases?  I'm looking at the source for `connect` [here](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L122).  To me, it seems this way relies on the connect component being rebuilt when we invalidate the tree.  I could just not understand the way react renders the tree though.

**Comment by skidding** [comment]
You don't have to worry about connect transition. When you set a different `key` to a child element React re-creates all instances, so the connect constructor will be called again. It's like loading a different fixture from scratch. Does this info help?

**Comment by JannesV** [comment]
This happens to me in non-test context aswell. If I supply a state or change the state in the component itself or in the code window it doesn't seem to update. If I disable the redux proxy however, all seems to work fine.

Passing `disableLocalState` to the redux proxy doesn't work either.

**Comment by dpearceglic** [comment]
I'm seeing the same behavior as @JannesV. If I define both ```state``` and ```reduxState``` in my fixture, local state for the component is not updated even with ```disableLocalState: false``` set in ```createReduxProxy``` in ```cosmos.proxies.js```. I've only been using Cosmos for 24 hours so I may be missing something basic, please forgive me if I am. The silver lining of this issue is that it showed me clearly that I wasn't encapsulating the responsibilities of both my dumb-component (local state expected to update with no knowledge of redux) and my smart-component (container).

**Comment by skidding** [comment]
The issue is that Cosmos can only access the outer-most component, which in the case of a Redux connected component is the `connect` decorator. Or some other HoC that the component is also wrapped in.

I'm now thinking of a next-gen API for fixtures that solves this long-standing issue. But atm you can only inject local state if the fixture points to the component with the state, not to a parent wrapper.

**Comment by skidding** [comment]
Side note: This might work already with React 16.3+ if react-redux forwarded the ref. [Relevant thread](https://github.com/reduxjs/react-redux/issues/914#issuecomment-383530758)

**Comment by skidding** [comment]
This issue belongs to http://github.com/react-cosmos/react-cosmos-classic, feel free to continue the discussion there.
