### ISSUE TITLE
react-cosmos-test globalImports

### ISSUE THREAD

**Issue by alexvpickering** [react-cosmos/react-cosmos#605]
### What's up?
I am trying to test a component that uses `jquery` with `react-cosmos-test`. `jquery` is attached globally to `window.$`. The component mounts in the App, and in cosmos after adding `globalImports: ["./src/include/jquery.js"]` to `cosmos.config.js`. How do I get `react-cosmos-test` to recognise global imports as well?

### Mkay, tell me more...

An example repo of the issue I am facing is [here](https://github.com/alexvpickering/cosmos-example)

Running `yarn test` currently fails with `TypeError: window.$ is not a function` before the test is run (during `mount`?). I tried adding `cosmosConfigPath` to `createTestContext` but that didn't work either.

**Comment by skidding** [comment]
Hey @alexvpickering 

`config.globalImports` is ignored by the test API. While I'm not sure of the full implications at the moment (ie. if we want the same globals in test environment as in Cosmos UI), it sounds like a good idea for a feature request. At the moment only `proxiesPath` is read from the cosmos config by the test API.

That said, I managed to make your repo work with the following changes:

```diff
# src/include/jquery.js
-import * as $ from "jquery";
+import $ from "jquery";
```
```diff
# src/setupTests.js
 import { configure } from "enzyme";
 import Adapter from "enzyme-adapter-react-16";
+import "./include/jquery";
```

`import * as $ from "jquery"` worked in the browser only (probably due to webpack magic), but `import $ from "jquery"` works universally.

Let me know if this helps.

**Comment by alexvpickering** [comment]
Hey @skidding 

Thank you - yes that resolved the immediate issue with `jquery`. It did however raise another issue in my actual code-base related to `datatables` (again, finding `$.DataTable` in `React`, `cosmos`, but not `cosmos tests`):

`TypeError: window.$(...).DataTable is not a function`

 I've reproduced the issue in the [example repo](https://github.com/alexvpickering/cosmos-example) if you're willing to take a look again.

Thank you for helping me to get started with `cosmos`. I'm finding it very useful so far.

**Comment by skidding** [comment]
A couple of things:

- Using a global namespace is no longer valid when working with CommonJS modules  (webpack, CRA, etc.), so you should import jQuery wherever you use it instead of reading it from `window`
- I'm not sure what's the best practice when dealing with jQuery plugins and CommonJS, or if there is a consistent one, but I managed to make your example to work: https://github.com/alexvpickering/cosmos-example/pull/1
- This is outside Cosmos' scope :)

**Comment by alexvpickering** [comment]
Ah that works now! Thank you so much. Wasn't aware of the distinction between the testing environment and the browser.
