### ISSUE TITLE
Make export deterministic

### ISSUE THREAD

**Issue by neezer** [react-cosmos/react-cosmos#620]
### What's up?

I run `cosmos-export` and I see that my generated files include absolute file paths specific to my system. When I have other team members contribute to my project and they run the same export, these files churn unnecessarily.

### Mkay, tell me more...

The files in question are

- `index.html`, in `mountPlayground`, argument `projectKey`: the value is an absolute path specific to the system the artifact was built on. Since I'm on a mac, it's value is similar to `/Users/myUserName/path/to/my/project`. This varies from developer-to-developer, so it churns.
- `loader/main.js`, in `fixtureModules` and `fixtureFiles[].filePath`: both also resolve using absolute file paths, so same problem as above.

I check-in my exported Cosmos because I host it on GitHub pages.

Since the static export seems to work just fine on GH pages, I'm guessing that the values for those keys aren't actually important to rendering/serving the site. If that's the case, can we make these relative to the project root so they don't churn when built on different systems? Or some other approach that won't build different artifacts if the code remains the same but the build environment changes?

Using `react-cosmos@3.7.1`

**Comment by skidding** [comment]
> I'm guessing that the values for those keys aren't actually important to rendering/serving the site

The file path is completely arbitrary. We need `projectKey` to be able to identify separate Cosmos projects (that run on same machine/host/port) when we save UI state in localStorage. Eg. which components are expanded in the tree view.

@neezer any ideas for a different identification source for `projectKey` that is identical across machines, but also doesn't change often (so that UI state is preserved)?

Ideas:
- package.json#name
- package.json#repository.url

Note that some projects might not have a name or repository in their package.json, so we either find a more consistent source or implement a fallback mechanism where the file path is used in case we can't rely on package.json data.

**Comment by skidding** [comment]
That said, that's only part of the "make export deterministic" issue. I just saw your [comment](https://github.com/kofile/react-components/pull/2#discussion_r174885705) and it's an interesting issue. It doesn't have anything to do with `playgroundOptions.projectKey`, but I think it's doable. 🤔

**Comment by neezer** [comment]
Don't see anything wrong with `package.json#name`. Between the two suggestions we know that [`name` should always be provided](https://docs.npmjs.com/files/package.json#name), whereas repository URL might be more variable.

> The most important things in your package.json are the name and version fields.

My two cents.

**Comment by neezer** [comment]
> It doesn't have anything to do with playgroundOptions.projectKey, but I think it's doable.

You sure? From that same [issue](https://github.com/kofile/react-components/pull/2):

<img width="1340" alt="screen shot 2018-03-20 at 12 35 24" src="https://user-images.githubusercontent.com/29997/37678420-43a52816-2c3b-11e8-8f6f-1ee9bc946fed.png">

**Comment by skidding** [comment]
Sure, `name` sounds good, although we should still fallback on project path, since it *is* possible for the name to be missing and we don't want to fail in that case.

So it seems like this boils down to two tasks:
- Make index.html deterministic by using `package.json#name` as identifier.
- Make main.js deterministic by embeding relative paths instead of absolute paths. Needs some research, but in theory we should be able to convert the absolute paths into relative paths before [statically including them in the bundle](https://github.com/react-cosmos/react-cosmos/blob/0aea3ff15cb0321c0ffbd319168b2d564ab07f75/packages/react-cosmos/src/server/embed-modules-webpack-loader.js#L105). Unless I'm missing something, they should be relative to [`packages/react-cosmos/src/client/user-modules.js`](https://github.com/react-cosmos/react-cosmos/blob/0aea3ff15cb0321c0ffbd319168b2d564ab07f75/packages/react-cosmos/src/client/user-modules.js), which is where the files are injected. I'd be interested in seeing a prototype for this if anybody's interested to experiment.

**Comment by skidding** [comment]
Good news @neezer,

The Cosmos project ID is now `package.json#name`, with fallback to the name of the immediate project directory. 

I've also fixed the 2nd issue where local paths ended up in the export bundle. It was as simple as using `require`s instead of `import`s when bundling the global user imports. Webpack-specific stuff...

Let me know if you still have issues if you get the chance to try the latest version (`react-cosmos@next`). Cheers!
