### ISSUE TITLE
Automagic folder generation question

### ISSUE THREAD

**Issue by SimeonC** [react-cosmos/react-cosmos#660]
I'm back with another one, think this is probably my mistake here.
Not really a big issue for me as I should probably be using some other method for this than subfolders but I thought I'd mention it.
![image](https://user-images.githubusercontent.com/1085899/39346834-131fa208-4a2b-11e8-9ff4-741c574447c4.png)
I did double check that my fixtures folder is called `__fixtures__`.
cosmos.config.js
```js
module.exports = {
  webpackConfigPath: '@tc-react-system/scripts/config/webpack.config.dev',
  publicPath: 'public',
  proxiesPath: 'src/cosmos/proxies',
  globalImports: ['src/cosmos/globals']
};
```

Using 4.0.0-rc.3

**Comment by SimeonC** [comment]
The component is `AdvancedEditor/Row.jsx`.
This only started happening when I nested ` __fixtures__/Row/basic.jsx`, when I had it as `__fixtures__/basicRow.jsx` it worked fine and appeared without the extra folders.

I think the fixture went a bit like this (left laptop at work so this is from memory).
```jsx
const Wrapper = (props) => (
  <div style={{background: ‘white’}}><TranslationRow {...props}/></div>
);
Wrapper.displayName = TranslationRow.displayName;

export default {
  name: ‘basic render (empty)’,
  component: Wrapper,
  ...other fixture data
};
```

**Comment by skidding** [comment]
Well, with that fixture Cosmos will think `Wrapper` is the component, and since it's placed in the fixture file it considers it the component file as well. (I realize this sounds logical to me because I'm intimate with the system, but might not from the outside.)

So you should make sure `fixture.component` points to your component. `TranslationRow` in your case.

How to add your wrapper?

### Option A: Create a [proxy](https://github.com/react-cosmos/react-cosmos#whats-a-proxy)

Example:

```js
// cosmos.proxies.js

const DEFAULT_BG_COLOR = 'transparent';

const BgColorProxy = ({ nextProxy, fixture, ...rest }) => {
  const { value: NextProxy, next } = nextProxy;
  return (
    <div style={{ background: fixture.bgColor || DEFAULT_BG_COLOR }}>
      <NextProxy nextProxy={next()} fixture={fixture} {...rest} />
    </div>
  );
};

export default [BgColorProxy];
```

Then your fixture will look like this:

```js
export default {
  name: ‘basic render (empty)’,
  component: TranslationRow,
  bgColor: 'white',
  ...other fixture data
};
```

### Option B: https://github.com/jozsi/react-cosmos-wrapper-proxy

**Comment by SimeonC** [comment]
Thanks for the clarity and solutions!
