### ISSUE TITLE
Passing an async function to react-cosmos-xhr-proxy?

### ISSUE THREAD

**Issue by p8952** [react-cosmos/react-cosmos#663]
Is it possible to pass an async function as a response when using react-cosmos-xhr-proxy?

I'd like to have a delay on XHR requests to better match real world usage of my components.

This appears to be supported in xhr-mock: https://github.com/jameslnewell/xhr-mock/issues/61 

Works (Immediate `Error: Request failed with status code 404` from Axios):
```
  {
    component: Applications,
    name: "02 Error",
    xhr: [
      {
        url: "/applications",
        response: (req, res) => {
          return res.status(404);
        }
      }
    ]
  }
```

Doesn't Work (Immediate `Error: Network Error` from Axios):
```
  {
    component: Applications,
    name: "03 Slow Error",
    xhr: [
      {
        url: "/applications",
        response: async (req, res) => {
          await delay(2500);
          return res.status(404);
        }
      }
    ]
  }
```

**Comment by skidding** [comment]
Hi @p8952,

This appears to be a shortcoming of the xhr-proxy. Under the hood the proxy uses xhr-mock, which [supports async responses](https://github.com/jameslnewell/xhr-mock/issues/61). So ideally your example should just work.

### Why doesn't it work?

Because the proxy component isn't aware that is has to wait, so the fixture is considered loaded instantly and the test runner goes to the next test.

### Can proxies halt fixture load execution?

Yes. 

Proxies receive a prop called `onComponentRef`. It is passed down until the leaf proxy which essentially loads the user component and calls onComponentRef when the `ref` of the user component's element is called. When this reaches the root proxy, it is considered that the fixture is loaded.

By hooking in into `onComponentRef` we can choose wait for some proxy-related activity to finish before bubbling up the component ref up the proxy component tree. The [state-proxy does this](https://github.com/react-cosmos/react-cosmos/blob/551af4aee1331c7bce2bee6b2389c3d146141e27/packages/react-cosmos-state-proxy/src/index.js#L122) already.

This might be confusing as it has Cosmos jargon, but I'm confident it can be achieved easily.

### Do we know when the xhr mock responses have resolved?

This is the meat. At the moment we [send the fixture responses blindly to xhr-mock](https://github.com/react-cosmos/react-cosmos/blob/551af4aee1331c7bce2bee6b2389c3d146141e27/packages/react-cosmos-xhr-proxy/src/index.js#L53).

I'd have to do some experimentation, but I suspect we can wrap all responses in a Promise, and then attach a resolve callback to the xhr-proxy component instance. And inside the `onComponentRef` callback we send to the child proxy, we await for the xhr-related promises to be resolved and only then call `props.onComponentRef`.

---

I'll try to give this a shot in a couple of days. But if you have the time and interest to tackle this yourself it would be even better and I'm here to assist.

Thanks for reporting this and sorry for the inconvenience!

**Comment by skidding** [comment]
I've thought about this some more and I don't understand how come this works without Cosmos, since the test still doesn't get any queue that it should wait until the request is resolved.

I'll investigate in a few days and get to the bottom of it.

**Comment by skidding** [comment]
Good news @p8952, I figured it out.

1. Cosmos was using xhr-proxy 1.x, which didn't support async responses. Upgrade to `react-cosmos-xhr-proxy@4.1.2` to get the latest xhr-proxy functionality.
2. Tests still won't wait until an async response is resolved, but you can tell them to!

Here's an working example:
- [fixture](https://github.com/skidding/react-testing-examples/blob/698a89c109fe4754f5b1591ead5d77db85008dd4/6-xhr/fixture.js)
- [test](https://github.com/skidding/react-testing-examples/blob/698a89c109fe4754f5b1591ead5d77db85008dd4/6-xhr/cosmos.test.js)

I use [async-until](https://github.com/skidding/async-until) in most of my tests nowadays. You first need to identify something that is rendered by the component before the request is resolved, like a loading message or a blank state. Then you tell the test to await until that element dissapears (with a given timeout), and only then assert the ready/data state.

Eg.

```js
it('renders data', async () => {
  await until(() => getWrapper('.loading').length === 0);
  // or 
  await until(() => !getWrapper().text().match('Loading'))
  // expect(...
});
```

Closing this for now, but let me know if this works for you!

**Comment by p8952** [comment]
@skidding Amazing, thanks very much!
