### ISSUE TITLE
How to integrate with Razzle

### ISSUE THREAD

**Issue by josemontiel** [react-cosmos/react-cosmos#668]
Hello,

Currently getting the following error for *.js React Components: 

> You may need an appropriate loader to handle this file type.

 when running `yarn cosmos`

Any help would be appreciated, Thanks!

**Comment by skidding** [comment]
Hi @josemontiel,

Is that the entire error message? Can you share a repo (your own or a minimal reproduction) that I can debug? Thanks!

**Comment by josemontiel** [comment]
Hello @skidding ,

Here's the entire error message:

> ERROR in ./src/components/PricingPlans/PricingPlansList.js
Module parse failed: ./src/components/PricingPlans/PricingPlansList.js Unexpected token (46:12)
You may need an appropriate loader to handle this file type.
| 
|         return (
|             \<div className={classes.root}>
|                 \<Grid container direction="column">
|                     \<Grid item>
 @ ./__fixtures__/PricingPlansList.fixture.js 1:0-79
 @ ./node_modules/react-cosmos/dist/client/user-modules.js
 @ ./node_modules/react-cosmos/dist/client/mount.js
 @ ./node_modules/react-cosmos/dist/client/loader-entry.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/client/loader-entry.js
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks  Chunk Names
                              index.html    567 kB       1  
    551193bb07773ee73ac5.hot-update.json  44 bytes          
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs 376 bytes {1}
       [1] ./node_modules/lodash/lodash.js 540 kB {1}
       [2] (webpack)/buildin/global.js 509 bytes {1}
       [3] (webpack)/buildin/module.js 517 bytes {1}


I will try to make a repo reproducing the issue and share ASAP.

Thanks!

**Comment by skidding** [comment]
Cosmos isn't picking up Razzle's Babel config. Can you please try creating this `.babelrc` file in your project root?

```
{
  "presets": [
    "razzle/babel"
  ]
}
```

**Comment by josemontiel** [comment]
Same error (from example repo project), @skidding :

>ERROR in ./src/Home.js
Module parse failed: Unexpected token (8:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       \<div className="Home">
|         \<h1>{this.props.title}</h1>
|       \</div>
 @ ./__fixtures__/Home.fixture.js 1:0-31 5:19-23
 @ ./node_modules/react-cosmos/dist/client/user-modules.js
 @ ./node_modules/react-cosmos/dist/client/mount.js
 @ ./node_modules/react-cosmos/dist/client/loader-entry.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/client/loader-entry.js
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  556 KiB       0  
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

**Comment by skidding** [comment]
Actually, after I added the `.babelrc` file the error changed:

> ERROR in ./src/react.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

Because the Cosmos config doesn't come equiped with loaders for every file type by default. In this situations it's good to reuse an existing config to avoid duplication. This is the first time I hear of Razzle, but after a quick check it doesn't seem to easily expose [its webpack config](https://github.com/jaredpalmer/razzle/blob/18cf1ab00d451a5db8fb121b6f30425ceb808255/packages/razzle/config/createConfig.js).

So if you comment the `import logo from './react.svg';` the setup works. But I've installed `file-loader` and added this to the Cosmos config:

```js
module.exports = {
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: 'file-loader'
    });
    return config;
  }
};
```

And now it works anyway. Depending on how many new loaders you'll need to add, this approach might or might not be suited for you, as you end up duplicating webpack config already built in in Razzle.

If you can't replicate this just give me access to the `razzle-cosmos-example` and I'll push my changes.

**Comment by josemontiel** [comment]
Thanks, @skidding ! I just went with adding the proper loaders on the `cosmos.config.js` file as you suggested and got Cosmos working 👍

**Comment by dan-weaver** [comment]
for future readers, this works well:

```javascript
var createRazzleConfig = require("razzle/config/createConfig");
var razzleWebpack = require("webpack");

module.exports = {
  webpack: (config, { env }) => {
    config.module.rules = createRazzleConfig(
      "web",
      "dev",
      {},
      razzleWebpack
    ).rules;
    return config;
  }
};
```
