### ISSUE TITLE
Add field in config for find-fixture-files method

### ISSUE THREAD

**Issue by mpachin** [react-cosmos/react-cosmos#687]
### What's up?

The project under discussion have such directory tree:

```
project
│
└─── node_modules
│   │
│   └─── ...
│   
└─── src
│   │
│   └─── node_modules
│   │   │
│   │   └─── @subproject1
│   │   │   │
│   │   │   └─── ...
│   │   │
│   │   └─── @subproject2
│   │   │   │
│   │   │   └─── ...
...
```
`@subproject`'s directories hold components which I want react-cosmos to keep track of.

Right now `cosmos.config.js` haven't field which could tell react-cosmos to not ignore subprojects in `./src/node_modules`, but keep ignore `./node_modules`, and that means I cant make react-cosmos display fixtures placed in there.

### Mkay, tell me more...

I'd like to add an optional field in `cosmos.config.js` which will [replace default value](https://github.com/react-cosmos/react-cosmos/blob/7e11e8a9f4c99c74c6f040358e9e99f9fc55643e/packages/react-cosmos-voyager2/src/server/find-fixture-files.js#L37) if specified.

**Comment by skidding** [comment]
I welcome this!

Note that there is already an `ignore` option which ends up as `exclude` in the `findFixtureFiles` function , to ignore certain files from the fixtures that have already been "collected". 

Since the current `ignore` option is a list of regular expressions, I doubt we can comfortably merge it with the new option you need. Although I'm open to discussion if you see a clear path.

The easier solution is a new option called something like `fileMatchIgnore`, specifically designed for the `ignore` option of the `glob` call, which defaults to `'**/node_modules/**'` to not affect backwards compatibility. Or `['**/node_modules/**']` if glob supports a list of globs.

**Comment by mpachin** [comment]
I think you right about the easier solution you described above, this is exactly how I see solution for issue.
Since we already cleared node_modules in `allPaths` variable:
```js
const allPaths = await globAsync('**/*', {
    cwd: rootPath,
    absolute: true,
    ignore: '**/node_modules/**'
});
```
We cant lay on `exclude` field from our config, because if we'll clear node_modules in allPaths there will be no point in clearing it again in
```
if (excludeList.some(excludePattern => filePath.match(excludePattern))) {
    continue;
}
```
I think what we need to do is to add new variable `fileMatchIgnore` as you described it, with fallback on `**/node_modules/**` by default.

**Comment by skidding** [comment]
@mpachin are you interested in making this contribution?

I can help with pointers and review.

**Comment by mpachin** [comment]
Yes, I am ☺️ I'll start working on it in nearest time

**Comment by crobinson42** [comment]
I spent longer than I want to admit looking for this `ignore` config option 🤦
