### ISSUE TITLE
cosmos-export strips fixture names, breaks some modules

### ISSUE THREAD

**Issue by good-idea** [react-cosmos/react-cosmos#701]
### What's up?

`cosmos-export` is stripping out the names of the fixtures it finds.

`cosmos`:

![image](https://user-images.githubusercontent.com/11514928/40899291-0a9c96f0-677b-11e8-8a70-5eb4147a8ae7.png)

`cosmos-export`:

![image](https://user-images.githubusercontent.com/11514928/40899301-1801ecfa-677b-11e8-862a-cdd614cb8866.png)

In the exported version, I also see this for some of the components:

![image](https://user-images.githubusercontent.com/11514928/40899790-8303d296-677d-11e8-80ad-102d15c9ff1c.png)

The console isn't very helpful:

![image](https://user-images.githubusercontent.com/11514928/40899807-98ab2130-677d-11e8-91f7-a198c45abe4f.png)

### Mkay, tell me more...

I'm not doing anything fancy with the config:

```
module.exports = {
	globalImports: ['./src/styles/global'],
	webpackConfigPath: 'none',
	watchDirs: ['./src'],
}
```

I have `webpackConfigPath` set to 'none' because I'm getting a bunch of other problems when trying to use it.

Everything is working as expected when it runs in development mode. Any clues on how I can start debugging this?

**Comment by skidding** [comment]
Hi @good-idea,

It seems like the component class/fn names are minified, which results in unintelligible labels inside Cosmos.

Try setting `NODE_ENV=development` when running the export command. It [defaults to "production"](https://github.com/react-cosmos/react-cosmos/blob/4a13b775617a031817008a8611e70db515dc355e/packages/react-cosmos/bin/cosmos-export.js#L4-L5), but it can be overridden.

> I have webpackConfigPath set to 'none' because I'm getting a bunch of other problems when trying to use it.

`null` would be a better value in this case. At the moment Cosmos tries to open a file called `none` and fails gracefully.

Still can't wrap my head around the `_extends is not defined` error, especially since you're relying on the default webpack config (unless the "none" value does something unexpected). Try running the export in development mode and then we'll take it from there. And if you have a public repo I can inspect let me know, I'll happily investigate.

**Comment by skidding** [comment]
I bumped into this as well. Will publish a fix soon!

**Comment by good-idea** [comment]
Hey @skidding, I tried making an export using `NODE_ENV=development` and that did the trick!

**Comment by skidding** [comment]
Fixed in [4.5.0](https://github.com/react-cosmos/react-cosmos/releases/tag/v4.5.0). No need to manually override the NODE_ENV anymore.

**Comment by good-idea** [comment]
🙌Thanks!

**Comment by kevin940726** [comment]
@skidding Looks like we don't need this anymore in cosmos next? Just a friendly reminder 😉.

**Comment by skidding** [comment]
@kevin940726 Yes, well the issue is already closed. :)

**Comment by kevin940726** [comment]
@skidding I meant that we can now enable the `minimize` option in prod build now?

**Comment by skidding** [comment]
Oh, good point. Yes, we no longer read component names for the fixture tree view, which is now 100% file system based. But we do read them for a feature that will be released later, which is a props editor where you can edit prop values that are shown under component names :D.

**Comment by kevin940726** [comment]
@skidding Perhaps we could provide babel plugin to skip minifying component names/injecting displayName, which is similar to how css-in-js like styled-components do to provide debuggable className. Maybe we can discuss it when the feature is in progress in another issue or in slack 😉
