### ISSUE TITLE
Possible to do shallow rendering?

### ISSUE THREAD

**Issue by jeznag** [react-cosmos/react-cosmos#744]
### What's up?
Cosmos seems really cool! I need to test context and it's doing that perfectly. 

One thing I'm wondering about is the possibility of doing shallow rendering. Not sure if that's completely taboo in the cosmos ecosystem? My motivation is I want to test one of my containers. I've got that working with a snapshot test but the snapshot is massive because it includes all of the child components.

From my perspective, I don't care about how the child components render from here. I figure as long as they're getting passed the right props (which is being tested by the redux proxy), they're probably fine and I'll test them in their own test.

### Mkay, tell me more...

My thinking is probably flawed here. Maybe a massive snapshot is expected and I should just deal with it. Perhaps I shouldn't actually write tests for the dumb child components if I'm just checking whether they render correctly?

Interested in your thoughts - maybe this question and answer could go into the README if shallow rendering is an antipattern.

**Comment by skidding** [comment]
Hi @jeznag,

Not out of the box, but it's possible. By changing [one line](https://github.com/react-cosmos/react-cosmos/blob/eb016f6be28b2134cb4264ec70266cf18ff4b7d8/packages/react-cosmos-test/src/enzyme.js#L40) you could pass the shallow renderer to Cosmos.

The main issue with shallow rendering, and why I went with mounting by default, is that the component you're testing is usually decorated by a number of wrapper components.

Like if you're testing a container, shallow rendering will only render the container and your component ends up being the child that is omitted. Moreover, Cosmos adds at least a wrapper component (and another one with each proxy configured), so to reach your component you have to go down a few levels down the rendering hierarchy. I believe you can keep calling `.shallow()` on a shallow Enzyme wrapper, but I didn't find that approach enjoyable while writing tests.

Finally, I like mounting because it behaves as close as possible to production code.

**Comment by jeznag** [comment]
Makes sense :)
