### ISSUE TITLE
Support deep nesting for fixtures in tree view

### ISSUE THREAD

**Issue by FL0RIANMEYER** [react-cosmos/react-cosmos#792]
### What's wrong?

If all the fixtures are in the same folder, there is no option to group names or namespaces
So there is a one or two layer treeview. But never through namespaces separated by chars like '/' or '\'.

### Screenshot
![image](https://user-images.githubusercontent.com/28124170/43930811-c6182c9c-9c3b-11e8-9d2d-e19531a2fc49.png)

### User info
react-cosmos@4.6.4

Would be nice to group by name or namespaces.

'app/login/simple'
'app/login/extended'
...

like https://github.com/react-cosmos/react-cosmos/issues/251

![image](https://user-images.githubusercontent.com/28124170/43930902-28037e20-9c3c-11e8-908f-235b464f48c9.png)

Even WrapperNames like Connect, Apollo, etc. are not very helpful

**Comment by skidding** [comment]
The problem is that currently the TreeView only supports one level of nesting for fixtures. Components on the other hand support an infinite level of nesting.

Example:

A component named `MyComp` with namespace `/path/to/comp` will appear like this in the tree view
```
path
  to
    comp
      MyComp
```

But a fixture named `myFixture` with namespace `/path/to/fixture` will appear like this in the tree view
```
path/to/fixture
  myFixture
```

I'll repurpose this issue into a feature request. [Here is the relevant code](https://github.com/react-cosmos/react-cosmos/blob/891b02b32b6db6e4d48e165228f941f34c72094f/packages/react-cosmos-playground/src/components/FixtureList/data-mapper.js#L18-L29)

**Comment by skidding** [comment]
No longer a limitation in Cosmos Next.
