### ISSUE TITLE
Provide/modify component props via query parameters

### ISSUE THREAD

**Issue by jeffal** [react-cosmos/react-cosmos#797]
Allow users to provide and modify component props via query parameters. This assists automated regression testing via [Cypress](https://www.cypress.io/).

Is this possible via https://github.com/react-cosmos/react-cosmos/tree/master/packages/react-querystring-router? I have been unable to implement the provided examples.

**Comment by skidding** [comment]
> Is this possible via https://github.com/react-cosmos/react-cosmos/tree/master/packages/react-querystring-router? I have been unable to implement the provided examples.

Wow, the docs on `react-querystring-router` are _old_. You do set the props via URL query string, but the props of the Cosmos UI—which is also a component, not of the component you load—which is rendered remotely in an iframe.

It wouldn't be that useful either as many prop values can't be serialized.

There are undocumented ways to remotely control the fixture, because this is how Cosmos works under the hood.  But before exploring uncharted territory, can you please share some test examples? It doesn't need to be real life data, but I'm curious about the use case. For example, why not create fixtures for prop combinations and just click through fixtures via Cypress?

**Comment by jeffal** [comment]
Hi @skidding, I am going to try dynamically modifying the Cosmos Code Mirror input via Cypress, otherwise, will create fixtures for all prop combinations. Thank you for the quick response!
