### ISSUE TITLE
Component path is broken in the cosmos playground tree when fixture data are generated on the fly

### ISSUE THREAD

**Issue by milheim** [react-cosmos/react-cosmos#835]
### What's wrong?

Component path is broken in the cosmos playground tree when fixture data are generated on the fly.

### Steps to reproduce

I have icon component with given directory structure:
```
@base
└── icon
    ├── __fixtures__
    |   └── icon.fixture.js
    ├── icon.component.js
    └── icon.config.json     
```
Where

`icon.config.json` is json mock data (Object[]),

`icon.component.js` is Icon component,

and

`icon.fixture.js` is Icon component fixture:
```javascript
import map from 'lodash/fp/map';

import Icon from '../icon.component';
import icons from '../icon.config.json';

export default map(icon => {
  return {
    component: Icon,
    name: icon.name,
    namespace: icon.size,
    props: {
      name: icon.name,
      size: icon.size
    }
  };
})(icons);
```
Here fixture data are generated on the fly based on `icon.config.json`.

I expect to see the following cosmos playground component tree:
```
@base
└── Icon
    ├── fixture folder (based on namespace)
        ├── fixture name (based on name)
        ...
        └── fixture name
    ...
    └── fixture folder      
```
Instead, I see:
```
Icon
├── fixture folder (based on namespace)
    ├── fixture name (based on name)
    ...
    └── fixture name
...
└── fixture folder 
```    

### Additional context

As I properly unterstood `getUserModules.fixtureFiles` are generated before real requiring of fixture module. Looks like static resolving of component name and filePath.

Based on this I found a workaround how to maintain proper cosmos playground component tree. 

I rewrote `icon.fixture.js` to:
```javascript
import map from 'lodash/fp/map';

import Icon from '../icon.component';
import icons from '../icon.config.json';

let fixture = {
  component: Icon
};

fixture = map(icon => {
  return {
    component: Icon,
    name: icon.name,
    namespace: icon.size,
    props: {
      name: icon.name,
      size: icon.size
    }
  };
})(icons);

export default fixture;
```
Now `getUserModules.fixtureFiles` return proper component and filePath but it looks odd.
 
### User info

- Browser console output: no issues
- Cosmos version: 4.7.0-3

**Comment by skidding** [comment]
> Component path is broken in the cosmos playground tree when fixture data are generated on the fly.

You are right, this is a limitation. As you said, the namespace is inferred statically from the component file path. The static analysis done is limited and cannot understand complex dynamically-generated fixtures.

The manual `namespace` property exists as a backup plan. I see you already use it for the fixture, but note that you can also set it for the component. The entire tree path is composed like this: `componentNamespace/componentName/fixtureNamespace/fixtureName`. Since the `componentNamespace` can't be identified statically (and isn't accessible at runtime), you can set it manually as well.

This solution is not very pretty either, but if you set `Icon.namespace = '@base'` I believe you'll achieve the desired effect.

**Comment by milheim** [comment]
Hello @skidding,

`namespace` looks better as temporary decision.
Thank you for sharing.
