### ISSUE TITLE
Observing prop change side effects.

### ISSUE THREAD

**Issue by cloudratha** [react-cosmos/react-cosmos#865]
Hey,

I just started using Cosmos, and so far loving it.

I have a component where a prop change causes UI side effects. Currently unobservable in Cosmos.

Currently it seems that changes to the FixtureEditor do not trigger lifecycle events down to the Playground Component, but rather remounts the component and subsequent Proxies (expected). First prize would be to allow the FixtureEditor to pass the props naturally, but I believe that would fundamentally change how people expect Cosmos to work. Unless a simple fixture option could enable this.

To solve this I have created a `buttonPropProxy`, which allows me to attach an array of prop changes (in the form of buttons) to the fixture which bubble down `onClick`. It works but it's not that great looking.

Can you suggest any places where I can hook into the existing UI to make this feel more natural?
Am I trying to fix a problem that is already solved?
 
Cheers!

**Comment by skidding** [comment]
Hi @cloudratha,

Props transition is not possible in Cosmos at the moment. But it will be. I'm currently hard at work on the next major version which will, among other things, have this functionality. You'll be able to choose whether to _reset_ or _transition_ props. And it will be using nice inputs for each prop, instead of one big JSON editor.

See the [README header](https://github.com/react-cosmos/react-cosmos/blob/6214636c2e7e86f633be2fb79133c784dcf58f60/README.md) and the included links for release information. I can't give exact estimations but I'm spending most of my time on this release.

Meanwhile, I'll leave this open in case anybody else has the same question.

**Comment by cloudratha** [comment]
Thanks for the quick reply.

I'll stick with my ugly `buttonPropProxy` for now then. Does the job.
Look forward to the next release.

Good work.
