### ISSUE TITLE
State mocking doesn't work with the redux proxy

### ISSUE THREAD

**Issue by justinglibert** [react-cosmos/react-cosmos#882]
### What's wrong?

State mocking doesn't work when you also use the redux proxy (and when you set reduxState)

### Steps to reproduce
**Fixture**
```javascript
import TestCosmos from "../TestCosmos";
export default {
    component: TestCosmos,
    state: {
        text: "No",
    },
    reduxState: {} //If you remove this line the state mocking works
};
```
**Component**
```javascript
import React, { Component } from 'react'

export default class TestCosmos extends Component {
  state = {
      text: 'Hey'
  }
  render() {
    return (
      <div>
        {this.state.text}
      </div>
    )
  }
}

```

### Additional context

You need to install the Redux proxy

**Comment by skidding** [comment]
Hi @justinglibert,

That is on purpose. The Redux proxy has a `disableLocalState` option that's [enabled by default](https://github.com/react-cosmos/react-cosmos/blob/7c110765da4ee948c2ea777dab683ea80fedc8b8/packages/react-cosmos-redux-proxy/src/index.js#L24). You can set it to `false` in your cosmos proxies file.

The reason why this was done (a _long_ time ago), was because having showing the state of Redux-connected components is a big nasty, you see a lot of internal Redux state...

Once react-redux starts using forwardRef this problem will go away completely.

**Comment by justinglibert** [comment]
Thank you for your fast answer 👍 ! I guess I didn't read the doc enough.
