### ISSUE TITLE
react-cosmos-redux-proxy 4.6.1 doesn't compatible with react-redux 6.0.0

### ISSUE THREAD

**Issue by calldanfeng** [react-cosmos/react-cosmos#903]
### What's wrong?

react-redux 6.0.0 was just released and there were some breaking changes: https://github.com/reduxjs/react-redux/releases
Using react-cosmos-redux-proxy 4.6.1 with react-redux 6.0.0 will get the following error:

> Could not find "store" in the context of "Connect(***)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(***) in connect options.

### Steps to reproduce

1.  Install "react-redux": "^6.0.0"
2. npm run cosmos

**Comment by skidding** [comment]
Hi @calldanfeng,

Thanks for reporting this, I can confirm it's true.

React Redux 6 switched from the old React context API to the new one ([source](https://github.com/reduxjs/react-redux/blob/849ce418fbfddacb5c6c4b818494f47412fba45a/src/components/Provider.js#L64-L70)). The Cosmos Redux proxy mimics the Redux provider, so it needs to be changed to use the new context API as well.

I believe the best strategy is to fork the `react-cosmos-redux-proxy` package into `react-cosmos-redux-proxy2` or `react-cosmos-redux-proxy6` (to match react-redux's version), to not disturb users who still depend on older versions of react-redux.

The work is fairly straightforward, but it still requires time. Time that unfortunately I can't spare at the moment, because I'm putting all my time and energy into shipping [Cosmos Next](https://github.com/react-cosmos/react-cosmos/blob/9a63bbfb937fa013840c279cba2b8da9cbc086a8/TODO.md#roadmap-cosmos-next) (which incidentally will make stuff like mocking Redux state more trivial, potentially without requiring any additional proxy).

I'll leave this open in case anyone else wants to help. I think the easiest course of action to provide relief to anyone wanting to upgrade to react-redux6 is to fork (ie. copy paste from monorepo) react-cosmos-redux-proxy into a personal repo, and publish a separate package that only works with react-redux6 and above. **I'm willing to provide guidance and review such a repo if anyone is interested!**

I've added a [mention](https://github.com/react-cosmos/react-cosmos/pull/906) in the README about this.

**Comment by calldanfeng** [comment]
Hi @skidding,
Thanks a lot for your quick response and I really appreciate your work on Cosmos Next. 
I've downgraded react-redux to 5.x.x in our project since there isn't a strong need in our team to use v6. As for react-cosmos-redux-proxy 4.x.x, I don't think it has to support react-redux v6 according to semantic versioning. 
Looking forward to your Cosmos Next!

**Comment by andyrichardson** [comment]
Hey folks, I've [opened a PR](https://github.com/react-cosmos/react-cosmos/pull/923) which should fix this.

The implementation uses _redux_ and _react-redux_ via peer dependencies rather than implementing a custom solution. It's a fair deviation from the prior implementation so let me know if there's anything about this approach that might not work.

**Comment by skidding** [comment]
Great news everyone!

You can use the latest react-redux version with Cosmos Next. Here's a brand new `ReduxMock` decorator for JSX fixtures: https://github.com/skidding/react-cosmos-redux

Let me know if you get a chance to try it!

> PS. Take a look at the source code if you're interested in how decorators are created. This one has some complexity due to state sync but it's written using _hooks_ and is actually pretty readable 💃.

**Comment by skidding** [comment]
Reopen in https://github.com/react-cosmos/react-cosmos-classic if needed. The newer `react-cosmos-redux` works with react-redux@6 and will also work with react-redux@7 when I find some time :).
