### ISSUE TITLE
`noEmit: false` in `tsconfig.json` — docs/defaults

### ISSUE THREAD

**Issue by haf** [react-cosmos/react-cosmos#998]
### What's wrong?

<img width="459" alt="Screenshot 2019-07-17 at 21 38 32" src="https://user-images.githubusercontent.com/193115/61405974-3dd23000-a8db-11e9-8a8e-e5ef94b7a18c.png">

By some "default"/modern TS `tsconfig.json`, `noEmit` is set to `true`, causing the `ts-loader` to say `Typescript emitted no output`. Presumably this is off for a reason, perhaps because it conflicts with something that nextjs does. In any case it should be documented that `noEmit` must be set to false.

**Comment by skidding** [comment]
@haf Can you please provide more context? Cosmos merely includes a webpack rule for `ts-loader` in the generated webpack config when ts-loader is installed locally. It has no knowledge of TypeScript.

**Comment by haf** [comment]
There's normally a `tsconfig.json` file in TS projects; and if it has the setting `noEmit: true`, then cosmos crashes with the above error.

**Comment by skidding** [comment]
This is likely an issue with Cosmos + Next.js.

Cosmos tries to generate a webpack config from scratch for your project by default. It is a naive approach but works is many cases. When it fails you can always point Cosmos to your existing webpack config. Next.js, however, fails to expose that config, so I'm afraid it is up to you configure your webpack config and hand it to Cosmos. There are two ways, either via `webpack.configPath` or `webpack.overridePath`.

I'm not an expert in Next.js and trying to adapt Cosmos to it is not a good idea as Next.js' config is very opinionated and changes often. If you can provide an example repo I can help you with the configuration and maybe we can learn something from that and improve Cosmos defaults or documentation. Otherwise it's impossible for me to help.

Thanks!

**Comment by haf** [comment]
Thank you for your reply. #1000 is a bug in the context you describe, but not this. This is only about `tsconfig.json`, which is user-supplied and doesn't change very often, so it should be enough to document the behaviour, as nextjs doesn't supply its own tsconfig.

That said, for #1000 I would very much like to create a sample that we work on together.

**Comment by skidding** [comment]
> as nextjs doesn't supply its own tsconfig.

It's very likely that Next.js transforms your tsconfig before using it.

**Comment by haf** [comment]
Relevant issue in the nextjs issue tracker: https://github.com/zeit/next.js/pull/7451

**Comment by skidding** [comment]
It makes sense to create separate threads for separate issues. My point was that it's not clear what the exact issue is yet and until we figure it out it's probably easier to have a single thread.

> Relevant issue in the nextjs issue tracker: zeit/next.js#7451

I saw that too, but it's not very clear because supposedly they're not overriding it any more. If only they exposed their webpack config, it would be so much easier to integrate :(.

Are you planning to create a minimal repo with your issue(s)? I can usually get to the bottom of a webpack related issue once I get my hands on a (minimal) repo I can clone. Once we fix it we can create proper issues to improve the experience of future users.

**Comment by haf** [comment]
Not with this issue; it's easily fixed and nextjs compilation still works with `noEmit: false`. This is about docs only.

**Comment by haf** [comment]
Red herring.
